LICENSE
README.md
code-of-conduct.md
project.md

*: add common files from runtime-spec

---

README.md

Redundant with the MAINTAINERS file.

README: remove Maintainers

---

README.md

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Make title similar to the runtime specification

---

README.md

ReadMe: Link to shared Code of Conduct in TOB repo

---

manifest.md

manifest: fix JSON commas

---

schema/defs-image.json
schema/image-manifest-schema.json

schema: switch Object to Descriptor

---

schema/manifest-list-schema.json

schema: use correct reference for manifestDescriptor

---

manifest.md
media-types.md

layout the media/mime types into their own page. Also add a type for the serialized combined layout (related to #23 and #38).
Next steps would be to make a compatibility matrix of types.

Media types page

---

serialization.md

from https://github.com/docker/docker/pull/22264
specifically commit a0237314277148093987380edc10222e63ba19e2
See also https://github.com/opencontainers/image-spec/issues/36#issuecomment-215175217

serialization: rebase on docker draft

---

.travis.yml

ensure the JSON examples in the documentation validates.

travis: validate examples

---

manifest.md

Should fix [this][1].
[1]: https://travis-ci.org/opencontainers/image-spec/builds/126777631#L176

manifest: Remove trailing comma from annotations.key2

---

serialization.md

Caused by https://github.com/opencontainers/image-spec/pull/49

serialization: fixing layout regression

---

manifest.md

Fixes https://github.com/opencontainers/image-spec/issues/53
Reported-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>

manifest: fixing mediatype reference

---

serialization.md

Recognized while implementing validation code for it.

serialization: format the config example as valid JSON

---

README.md

Add an initial pointer for the spec(s)

---

serialization.md

A small fix from the v1.1 merge that happened inside of the docker repo
after we pulled this in.
See https://github.com/docker/docker/pull/22264

serialization: add language improvement to serialization

---

Makefile

Makefile: fix the image paths for docs

---

manifest.md

[Manifest] Fix typo

---

manifest.md

Clarifies that digest is required per Issue #103
Closes #103

[Manifest] Mark digest as required

---

manifest.md

Per discussion in #113, this is REQUIRED

[Manifest] Mark config as required

---

schema/config_test.go
schema/manifest_test.go

Currently samples in the specification are being tested. This adds
additional tests.
Closes #83.

schema: add more tests

---

media-types.md
schema/schema.go

leftover form #95 fwict
/cc @philips @vbatts 

*: remove references to combined schema

---

image-layout.md

/cc @vbatts @philips see individual commits messages for context

image-layout.md: fixes

---

serialization.md

This fixes https://github.com/opencontainers/image-spec/issues/130

serialization: add language about whiteout

---

media-types.md

media-types.md: fix typo

---

schema/spec_test.go

schema: close files

---

manifest.md

manifest: explain schemaVersion == 2

---

Makefile
schema/config-schema.json
schema/defs-config.json

Makefile: fix fmt target and format json files

---

schema/manifest_backwards_compatibility_test.go

Build on top of #151 and #152
commit https://github.com/opencontainers/image-spec/pull/154/commits/1d75bf1d48e216b66e86cc09bfbcb22154b4c702 adds manifest list test

test: manifest list backward compatibility

---

README.md

Add a working call-in number

---

glide.lock
glide.yaml
vendor/github.com/russross/blackfriday/LICENSE.txt
vendor/github.com/russross/blackfriday/block.go
vendor/github.com/russross/blackfriday/html.go
vendor/github.com/russross/blackfriday/inline.go
vendor/github.com/russross/blackfriday/latex.go
vendor/github.com/russross/blackfriday/markdown.go
vendor/github.com/russross/blackfriday/smartypants.go
vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
vendor/github.com/shurcooL/sanitized_anchor_name/main.go
vendor/github.com/spf13/cobra/command.go

vendor missing dependencies

---

Makefile

Makefile: add helpers for glide-vc and !glide installed

---

GOVERNANCE.md
RELEASES.md

https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/x-Oh3PDz1Y8

Add governance and release process

---

.tool/lint
.travis.yml
image/manifest.go

This was causing a lint failure https://travis-ci.org/opencontainers/image-spec/builds/148403656#L247

image: reduce permissions on mkdir

---

image/image.go

What is the double `given` mean? I'm not sure if it's a typo :)

Typo: remove duplicate given

---

cmd/oci-image-tool/man/oci-image-tool-create-runtime-bundle.1.md

Fix typo in man page for oci-image-tool

---

serialization.md
specs-go/v1/config.go

Typo: use entrypoint instead of entry point

---

serialization.md

This is a pass at explaining the concept of opaque files and their role in the specification. Provides recommendations that implementations should generate explicit format, but accept opaques.
cc @vbatts @runcom @philips 
Closes #144

serialization: describe the role of opaque whiteout files

---

specs-go/descriptor.go

Typo: fix typo in descriptor.go

---

ChangeLog

This doesn't include everything but the highlights of the PRs and issues
closed.

ChangeLog: add the v0.4.0 release notes

---

cmd/oci-image-tool/README.md

[ReadMe] Update example to v0.4.0

---

manifest.md

manifest: remove carry-over cruft

---

image/walker.go

These line seem repeated, remove one copy of it.
Signed-off-by: Deng Guangxing <dengguangxing@huawei.com>

remove redundant code

---

descriptor.md

typo: fix a url

---

image-layout.md

image-layout: use slash separated hierarchy for blob storage

---

layer.md

Typo: fix a typo in layer.md

---

image-layout.md

Fix link in image-layout.md

---

serialization.md

Fix link to layer.md

---

layer.md

layer: add use of "entries" for "files" in tar

---

media-types.md

media-types: break up sentence into multiple lines

---

media-types.md

media-type: clarify that we have MIME-compatible media types

---

image-layout.md

Corrected word: appropriate
Signed-off-by: Kushal Das <mail@kushaldas.in>

Fixes small typo

---

serialization.md

Use changeset instead of change set

---

serialization.md

Typo: remove comma in example json of volume

---

HACKING.md

HACKING.md:jq should be version 1.5 or higher

---

layer.md

Fixes: #306 
/cc @stevvooe @philips 

layer: add hardlink handling information

---

config.md

Originally proposed by @coolljt0725 in #301 and [not carried][1] by #333.
[1]: https://github.com/opencontainers/image-spec/pull/333#issuecomment-249770880

config: Cross-link ImageID and image JSON

---

specs-go/version.go

it appears i missed rev'ing the version for v0.4.0, so this is a jump from 0.3.0-dev -> v0.5.0

v0.5.0 bump

---

config.md

[As][1] [suggested][2] for #333.
[1]: https://github.com/opencontainers/image-spec/pull/333/files#r79975924
[2]: https://github.com/opencontainers/image-spec/pull/333#issuecomment-249000454

config: One line per sentence for Volumes description

---

image-layout.md

image-layout: minor syntax fixes

---

MAINTAINERS

[Maintainers] Update email for Brendan Burns

---

layer.md

layer: fix plural (media type -> media types)

---

config.md
image-layout.md
manifest.md
media-types.md

Consolidate "OpenContainers", "Open Containers" -> "OCI"

*: make document titles more consistent

---

README.md

README: fix link syntax

---

config.md

Remove unnecessary blank line.
ping @philips

config.md: some minor format fix

---

image-layout.md

image-layout.md: fix link to layer.md

---

README.md

README.md: one sentence per line

---

image-layout.md

refs can point to an image manifest list

---

specs-go/v1/layout.go

Add license head to layout.go

---

.tool/check-license

tools: fix license header check

---

image-layout.md

this big section looks a little hard to read, so I set it to paragraphs.

set paragraph to massive description

---

config.md

config.md: fix some typo

---

descriptor.md

descriptor.md: of size->and size of

---

media-types.md

media-types.md: be->are

---

manifest-list.md

The filed name is `manifests` but not manifest.

manifest-list.md: in the manifest-> in `manifests`

---

README.md

Signed-off-by: Ling FaKe lingfake@huawei.com

README.md: fix wrong place of period

---

specs-go/version.go

Awaiting vote --> https://groups.google.com/a/opencontainers.org/d/msg/dev/IUhd1CoXmC8/1jDkvivwDAAJ

Version bump

---

schema/config_test.go

config_test.go: Improve the verification content

---

schema/manifest_test.go

manifest_test.go: Improve the test content

---

image-layout.md

This should format the output as standard JSON, as above JSON objects.

format to standard output on JSON blob in image-layout

---

image-layout.md

Signed-off-by: Lei Jitang <leijtiang@huawei.com>

Typo: add missing period at the end of line

---

image-layout.md

Change `Manifest List` to `Image Index`

---

specs-go/version.go

90c67b0 Merge pull request #575 from coolljt0725/fix_ref
e0f3d4b Merge pull request #574 from wking/auxilary-typo
a125828 Merge pull request #546 from vbatts/manifest-list-rename
2a0114e Merge pull request #571 from vbatts/makefile_default_target
a651ad6 Merge pull request #572 from coolljt0725/fix_typo
bba6ed8 Merge pull request #551 from stevvooe/annotations-field-on-descriptor
5ef499e Merge pull request #563 from xiekeyang/compatibility-test
c91797c Merge pull request #564 from xiekeyang/config-schema
c16fa01 Merge pull request #519 from coolljt0725/validate_layout
87410cf Merge pull request #565 from vbatts/fixup_pr533
df12019 Merge pull request #559 from vbatts/carry_pr497
e4c7ecd Merge pull request #561 from wking/no-refs-catchup
145870b Merge pull request #555 from …

Bump version

---

schema/descriptor_test.go

descriptor-test: add test

---

manifest.md

Fix broken link

---

.tool/lint

I commit as individual patch as I found this bug is blocking CIs of other patchs. PTAL.

Extension of deadline in make lint

---

implementations.md

The repository has moved and I would like to make sure the reference is current.
I hope this is a welcome change. Thank you!

Rename box repository in implementations.md

---

spec.md

Catching up with [erratum 499][1].
[1]: https://www.rfc-editor.org/errata_search.php?rfc=2119

spec: Add "NOT RECOMMENDED" to RFC 2119 keywords

---

layer.md

layer.md: fix broken link

---

descriptor.md

descriptor.md: fix broken link

---

manifest.md

manifest.md: fix broken link

---

descriptor.md

descriptor: digest example link should be SHA-512

---

annotations.md

annotations: fix a hyperlink

---

descriptor.md

fix bad link

---

specs-go/version.go

PRs merged since rc6:
#672 stevvooe/remove-features-field
#680 wking/spdx-license-expressions
#678 vbatts/annotations_cleanup_1
#656 AkihiroSuda/optional-blob
#679 xiekeyang/bad-link
#676 stevvooe/label-schema-compatibility-table
#650 AkihiroSuda/platform-variant
#677 AkihiroSuda/fix-typo
#674 Mashimiao/consistent-filesystem
#667 AkihiroSuda/sha256-chars
#668 wking/supported-to-registered
#666 stevvooe/digest-examples-typo
#673 Mashimiao/config-typo-sentence-fix
#669 Mashimiao/config-small-fix
#670 Mashimiao/manifest-fix-broken-link
#663 Mashimiao/descriptor-fix-link
#664 Mashimiao/layer-fix-link
#654 stevvooe/future-proof-digest-constraints
#634 stevvooe/restrict-references
#649 qianzhangxa/master
#609 jonboulle/algorithms
#653 AkihiroSuda/lint-deadline
#660 mattspencer-arm/master
#636 …

Bump version to rc6

---

schema/imageindex_test.go

schema: minor formatting fix in tests

---

schema/fs.go
schema/image-index-schema.json

schema: delete extra characters

---

schema/validator.go

schema: add check platform to manifests

---

schema/fs.go
schema/imagelayout_test.go

schema: add layout test

---

schema/fs.go
schema/imageindex_test.go

imageindex_test.go: fix test

---

specs-go/version.go

The vote for this version: https://groups.google.com/a/opencontainers.org/d/msg/dev/JLRTrSTeAAg/m2dWf0ZuAwAJ
Since the [rc6 release](https://github.com/opencontainers/image-spec/releases/tag/v1.0.0-rc6) there have 22 changesets merged:
#707
#704
#705
#706
#703
#702
#652
#701
#694
#693
#695
#700
#699
#696
#671
#688
#691
#689
#492
#685
#491
#683

bump to v1.0.0-rc7

---

README.md

README.md: update description about the roadmap

---

schema/validator.go

validate: change manifestlist to index

---

descriptor.md
image-layout.md

descriptor.md: fix digest link

---

image-index.md

Signed-off-by: Eli Young <elyscape@gmail.com>

Fix formatting of platform.os.features values list

---

schema/validator.go

validate: add '\n'

---

README.md

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
Here is 3/3, updating the code of conduct link.

updating link to code of conduct in org repository

---

README.md

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

fixing code of conduct link

---

.travis.yml
schema/loader.go

Make error string non-capitalized, to fix linting problem.
This will (most likely) make CI pass again.

Fix linting error

---

MAINTAINERS

I have not been active in the project for quite some time so I am
stepping down.
Thank you for all of the work over the years to standardize container
formats everyone!

MAINTAINERS: remove Brandon Philips @philips

---

.travis.yml
Makefile

pandoc: point to a joint OCI org image

---

EMERITUS.md

Previous maintainers should be thanked for their work.

Create EMERITUS.md to recognize old maintainers

---

Makefile

like
https://github.com/opencontainers/distribution-spec/commit/199cf0e5f696a09557b2d7e1ab9b065dcacf5317#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

Makefile: switch to the new OCI container image

---

CODEOWNERS

CODEOWNERS: switching from pullapprove to github builtin

---

implementations.md

Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

Reflect docker donation of distribution to CNCF

---

implementations.md

Add ACR to Implementations
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

Add ACR to Implementations

---

implementations.md

Add regclient to implementations

---

implementations.md

implementations||adopter: point to krustlet/oci-distribution

---

RELEASES.md

Copy over release doc from http://github.com/opencontainers/runtime-spec/blob/main/RELEASES.md
Signed-off-by: Sajay Antony <sajaya@microsoft.com>
Note: Can be merged after the vote/release of RC1.

docs: Update release process docs with checklist

---

artifact.md

Fix the example to be a valid JSON object.
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>

doc: fix example in artifact.md

---

schema/validator.go

This keeps breaking CI for the PR's, so I'm pulling it out to a separate change that I hope is an easy approve.

Fix unused variable linting error

---

annotations.md

Fix the spelling of superseded

Fix a typo in the annotations spec

---

README.md

Remove IRC link

---

README.md
project.md

This file is redundant and conflicting with the RELEASES.md content.

Delete project documentation
