- .travis.yml
Starting with git commit validation.
Travis integration will still need to be enabled.
> travis: add initial checks

- manifest.md
- serialization.md
Per the proposal for this image-spec group, this is bringing in the base for the distributable image format from https://github.com/docker/distribution/blob/bf9f80eaffb0eabc768762bc4ff03ded277ea594/docs/spec/manifest-v2-2.md and https://github.com/docker/docker/blob/99a396902f0ea9d81ef87a683489b2435408f415/image/spec/v1.md
> Initial import of specs

- README.md
Open question is whether we should just delete this section and replace it with milestones all together.
> README: update to point to GitHub milestones

- manifest.md
- serialization.md
As #6 was tangled up with WIP modifications, this splits out into a new PR all the modifications.
> Begin adjustments on the imported specs

- schema/Makefile
- schema/defs-image.json
- schema/defs.json
- schema/image-manifest-schema.json
- schema/validate.go
related to #7 
testing against https://gist.github.com/vbatts/b3e4fc231fbc92a9cbc28b9184f0b2d2
> Json schema for image manifest and manifest list

- schema/image-manifest-schema.json
- schema/manifest-list-schema.json
I managed to forget adding the file in
https://github.com/opencontainers/image-spec/pull/18
> schema: actually add the schema file

- manifest.md
- schema/defs-image.json
- schema/image-manifest-schema.json
- schema/manifest-list-schema.json
This introduces OPTIONAL annotations, which are consistent with the
annotations in the runtime-spec.
While the spec does not exclude use of arbitrary fields, this OPTIONAL
property gives a guided place for manifest authors to isolate their
arbitrary metadata.
> manifest: add annotations

- .gitignore
- Makefile
- README.md
- serialization.md
This adds a `docs` make target for producing a PDF and HTML.
The output of `tree` in `./serialization.md` does not jive with pandoc.
Not sure what better visual layout of a directory tree we can use.
This also pins the version of code-of-conduct, instead of just master.
Fixes #16
> docs: make target for PDF and HTML

- manifest.md
- The meaning of "base" isn't terribly clear.
- In OCI "version 1" isn't useful.
> manifest: try to clear up the langauge on layers

- media-types.md
In an effort to help people implementing registries or systems that
consume the OCI Image specification and other image formats start a list
of compatible mime-types.
Fixes https://github.com/opencontainers/image-spec/issues/14
Take some language from the discussion here: https://github.com/opencontainers/image-spec/issues/42
> media-types: add a compatbility list

- serialization.md
Signed-off-by: Timothy Hobbs <timothyhobbs@seznam.cz>
> Specify process for naming future architectures

- serialization.md
This spec started from the Docker v1.10 serialization notes but we need
to give it its own identity. So, remove mentions of Docker that aren't
material to the spec.
> serialization: remove references to docker

- manifest.md
> Minor tweaks to manifest for clarity

- manifest.md
For a number of images, source code needs to be provided due to the
license of the files in the image, so provide an annotation to make it
easy to determine where that source can be found.
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
> image manifest: add source annotation

- schema/fs.go
- schema/gen.go
Currently *.go files are encoded in the embedded schema file system.
This fixes the ignore pattern for esc for go generate.
Fixes #79
> schema: remove *.go files from embedded fs

- Makefile
- media-types.md
Due to pandoc pdf and html wanting a uri to reference an image, we'll
need images to be inlined fo rthe document. So with this, the document
will get an base64 blob of images that match the target 'inline-png-%.md'
See also https://github.com/opencontainers/image-spec/issues/70#issuecomment-217656058
> inline images: media-types.png is inline

- cmd/oci-image-tool/validate.go
- schema/config-schema.json
- schema/defs-config.json
- schema/defs.json
- schema/fs.go
- schema/schema.go
- schema/spec_test.go
- serialization.md
> schema: add config/image JSON schema and validation

- README.md
We have the roadmap encoded into GitHub issues. Just point there
instead.
> README: remove the roadmap

- Makefile
This binary was removed in a previous commit but the make targets were
not. The make targets have now been removed and the `validate-examples`
targets run the schema tests on the spec files.
> Makefile: remove oci-validate-examples target

- .gitignore
- cmd/oci-image-tool/autodetect.go
- cmd/oci-image-tool/unpack.go
- cmd/oci-image-tool/validate.go
- image/descriptor.go
- image/doc.go
- image/image.go
- image/manifest.go
- image/walker.go
> layout: implement unpacking and validation

- .travis.yml
This will likely currently fail, as the pandoc is grumpy with the image references in master, but such is a good test case that it should fail CI if that happens.
> travis: make the docs in CI

- README.md
Many of the OCI image spec maintainers didn't know about this call. Add
it.
> README: add the weekly call

- .pullapprove.yml
Ensure that OCI projects share the same approval settings, this has been done for the runtime-spec and runc already, so it makes sense to do the same for image-spec:
https://github.com/opencontainers/project-template/issues/4
https://pullapprove.com/opencontainers/image-spec/
> Add PullApprove support to enforce consistent review 

- Makefile
- media-types.md
This includes:
* better doc filename, and variablized for ease
* inline images do not seem needed now. put the media-types back
Closes #90 
> *: fixup the docs output

- .pullapprove.yml
'^(Approved|lgtm|LGTM|:shipit:|:star:|:\+1:|:ship:)'
> Fix the PullApprove approve_regex to cover more cases

- .travis.yml
- Makefile
> travis: use a `make .gitvalidation` target

- README.md
Replaces "should strive" below with "strives" since "should" could be construed to have specific meaning per RFC2119
> Q: What happens to AppC or Docker Image Formats?
> A: ... The OCI Image Format project should strive to provide a dependable open specification ...
> [ReadMe] remove "should" from FAQ question

- .tool/check-license
- Makefile
Bash requires `echo -e` to [enable interpretation of backslash
escapes][1], but POSIX [does not standardize any options for
`echo`][2].  From the [POSIX docs][2]:
> It is not possible to use echo portably across all POSIX systems
> unless both -n (as the first argument) and escape sequences are
> omitted.
>
> The printf utility can be used portably to emulate any of the
> traditional behaviors of the echo utility as follows...
`printf` is a better bet.  From the [POSIX docs][3]:
> The printf utility was added to provide functionality that has
> historically been provided by echo.  However, due to irreconcilable
> differences in the various versions of echo extant, the version has
> few special features, leaving those to this new printf utility,
> which is based on one in the Ninth Edition …
> *: Remove 'echo -e ...' (use 'echo' and 'printf')

- cmd/oci-image-tool/autodetect.go
- cmd/oci-image-tool/validate.go
- schema/error.go
- schema/validator.go
Previously no line/col information was provided if JSON parsing failed.
This fixes it.
Unfortunately we still cannot determine line/col information in case of
schema validation because the original JSON decoderState is lost.
> schema: add line/col info in case of JSON err

- manifest.md
This section essentially talks about the HTTP registry API. OCI doesn't
have the concept of a HTTP transport so drop the entire section. We
should add this sort of language later once we sort out in the OCI TDC
making an HTTP transport.
> manifest.md: remove backwards compatibility section that refers to registries

- README.md
Based on feedback new users might not know what the base and optional
layer language is about. Point to the scope doc that uses this language.
Fixes #120.
> README: add language around base and optional layers

- descriptor.md
- media-types.md
- schema/content-descriptor.json
- schema/defs-image.json
- schema/fs.go
- schema/image-manifest-schema.json
- schema/schema.go
- schema/spec_test.go
Add a definition for content descriptors and digests, which are used as
content identifiers in the OCI image specification.
This is a draft of the descriptor specification, which includes the digest calculation.
Before merging:
Closes #92 
cc @philips @vbatts
> spec: describe descriptors and digests

- cmd/oci-image-tool/create_runtime_bundle.go
- cmd/oci-image-tool/main.go
- image/config.go
- image/image.go
This is a first shot towards a `oci-image-tool create-runtime-bundle` subcommand.
I found that converting towards the runtime bundle we have (obviously) quite some impedance mismatch here and there so I guess I surely missed something.
The most important questions for me are:
- What `ociVersion` to I have to set?
- How to map image `Volumes` to bundle `mounts`?
- Is there anything else obvious I am missing?
- We have redundant declarations of layers, one in the manifest, one in the image JSON, it is not clear to me which layer declaration is the one I should pick for unpacking to the bundle. This also applies to unpack. I opened https://github.com/opencontainers/image-spec/issues/115 for this.
Generally I have the impression that I can only fill up only a small subset of the bundle …
> oci-image-tool: implement create-runtime-bundle

- image-layout.md
In order to build tooling that converts the set of OCI Image objects
into an OCI Runtime object we need an Image Layout that test tools can
be built around.
Longer term this Image Layout could be used to define a "single object
image" that is a tar/zip/etc that could be posted over https/ftp/etc.
The layout comes from several different discussions:
https://github.com/opencontainers/image-spec/issues/23
https://github.com/opencontainers/image-spec/issues/92
> image-layout: add an initial image layout spec

- image-layout.md
Fix #132 
Fix #134
/cc @vbatts @philips
> image-layout: clarification

- schema/config_test.go
- serialization.md
These quasi-entities (which are missing the usual closing semicolon)
have been floating around since c22ca799 (serialization: docker v1
image format media type, 2016-04-04, #6).
Generated with:
$ sed -i 's/&lt/</;s/&gt/>/' $(git grep -l alyspdev@example.com)
> *: Fix '&lt' -> '<' and '&gt' -> '>' typos

- image-layout.md
As the refs are descriptors, the media-type is not strictly a manifest
or manifest-list.
https://github.com/opencontainers/image-spec/pull/137/files/790e2d3d5ec317a1d2fa6546ca956fdeb134a36a..346ca18588ba9fcb89aeffaa02facece66e6591a#r67184919
Reported-by: W. Trevor King <wking@tremily.us>
> image-layout: clarify refs can be generic

- manifest.md
Right now manifest is relying on the external Docker docs to explain the
digest format. Instead use the OCI Descriptor docs.
> manifest: use descriptor doc as canonical source

- schema/manifest_backwards_compatibility_test.go
This adds a test of the schema compatibility by taking the manifest of
library/docker from the Docker Hub, with sha256 digest verification, and
simply finding/replacing the four constant strings documented in
media-types.md and ensuring that it passes OCI validation.
https://github.com/opencontainers/image-spec/blob/master/media-types.md
This test is functionaly equivalent to downloading a Docker v2.2
manifest into the file `docker-manifest`:
```
$ curl -L -H "Authorization: Bearer ..." \
-H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
https://registry-1.docker.io/v2/library/docker/manifests/sha256fg:888206c77cd2811ec47e752ba291e5b7734e3ef137dfd222daadaca39a9f17bc > docker-manifest
```
And then running a regex to change `docker.distribution` to `oci.image`
and changing …
> schema: add a docker v2.2 backwards compat test

- schema/fs.go
`esc` has been updated to close file handler which wasn't https://github.com/mjibson/esc/pull/27
/cc @jonboulle 
> schema: update from updated esc command

- serialization.md
DiffIDs and Manifest list digests were a bit confusing. Explain the
difference.
Fixes: #115
> serialization: add explanation of DiffIDs

- Makefile
After mulling on https://github.com/opencontainers/image-spec/pull/148
perhaps removing the for loop is a bit more simple and safe.
Additionally, I opened upstream fixes for the whitespaces
* https://review.gerrithub.io/#/c/281914/
* https://github.com/pkg/errors/pull/61
> Makefile: comments and simplify

- specs-go/descriptor.go
- specs-go/v1/config.go
- specs-go/v1/manifest.go
- specs-go/v1/manifest_list.go
- specs-go/v1/mediatype.go
- specs-go/version.go
- specs-go/versioned.go
/cc @vbatts @stevvooe @philips 
This is another version https://github.com/opencontainers/image-spec/pull/147 w/o using any code generation tool - as discussed over there
Close https://github.com/opencontainers/image-spec/pull/147
> Export types

- manifest.md
1149faca (manifest: use descriptor doc as canonical source, 2016-06-15, #143) was a step in this direction.  But we can DRY things up a bit more by punting those three properties entirely and just saying "it's a descriptor", and then listing extensions, if any.
> manifest: Punt mediaType, size, and digest to descriptor docs

- cmd/oci-image-tool/man/oci-image-tool-create-runtime-bundle.1.md
- cmd/oci-image-tool/man/oci-image-tool-unpack.1.md
- cmd/oci-image-tool/man/oci-image-tool-validate.1.md
- cmd/oci-image-tool/man/oci-image-tool.1.md
> cmd/oci-image-tool: add manuals

- .tool/lint
- cmd/oci-image-tool/create_runtime_bundle.go
- image/config.go
- image/descriptor.go
- image/manifest.go
```sh
$ mkdir fedora-oci
$ skopeo copy docker://fedora oci:fedora-oci
$ mkdir fedora-bundle
$ oci-image-tool create-runtime-bundle --ref latest fedora-oci fedora-bundle
```
Eventually the extraction fails because of permissions but this is expected because `fedora` has `/root` populated while for instance `busybox` doesn't have it so the only option is to unpack as root:
```sh
$ oci-image-tool create-runtime-bundle --ref latest fedora-oci fedora-bundle
[...]
unpacking failed: error extracting layer: unable to open file: open fedora-bundle/rootfs/root/.bash_logout: permission denied
```
> Fix broken oci-image-tool

- descriptor.md
Correct digests-and`—`verification to digests-and`-`verification.
> Fix link in descriptor.md

- descriptor.md
- schema/content-descriptor.json
- schema/defs-image.json
> descriptor: size int64

- .pullapprove.yml
We use this in the runtime-spec and should use it here also.
https://github.com/pullapprove/support/pull/74
> PullApprove has support to check for DCO reqs

- cmd/oci-image-tool/README.md
Since this tool is usable on its own.
> oci-image-tool: add README

- cmd/oci-image-tool/man/oci-image-tool-create-runtime-bundle.1.md
runc seems should be executed as `run` here.
> correct example in bundle man

- image-layout.md
blob digest seems should be hex format based on sha256.
> correct blob digest set

- Makefile
Enable building the documents with a native pandoc.
Code pretty much taken directly from the similar series in the
runtime-specificaiton Makefile, such as in:
2e2073b (Makefile: Fix native pandoc invocation)
Signed-off-by: Graham Whaley <graham.whaley@linux.intel.com>
---
Note, I don't have the ability to check the docker run based build, just the pandoc one.
> Makefile: Enable native pandoc builds

- README.md
> [ReadMe] Adds boilerplate MUST, MAY, etc. language

- serialization.md
The `rootfs.type` field previously allowed a `type` of `layers+base` to
signify that there the layers must be applied to a base image. This was
required to support windows containers in Docker initially but has since
been replaced with a more compatible mechanism. It has no relevence for
OCI.
Closes #186.
@opencontainers/image-spec-maintainers PTAL
> serialization: remove windows-specific layers+base rootfs

- image/config.go
- image/descriptor.go
- image/manifest.go
- image/walker.go
1. walk functions had better to return `nil` in the case of no-error.
2. walk functions may not be defined as variable, but as function argument directly.
> improve walk function on returning result

- image/config.go
- image/descriptor.go
- image/manifest.go
- image/walker.go
Sorry it is my previous fault by #201 .
That patch leads the walk function exit incorrectly.
it is because that function `filepatch.Walk()` must not return error when meeting path mismatch error. Instead it should return nil. And the checking should be done in the end of walk.
Here I fix the bug in this patch. I retrieve old assertion block. I've run `create` , `validate` and `unpack` command according to the command manual successfully.
I will improve the mechanism gracefully.
PTAL, Thanks lots!
> bugfix: walk function exit incorrectly

- serialization.md
These are not used anywhere else in this repository at the moment, and we can always dig them back out of the Git history if/when we need them for naming.
> serialization: Drop "Tag" and "Repository" terms

- image-layout.md
> image-layout: add explanation of the refs directory use case for tags

- cmd/oci-image-tool/man/oci-image-tool.1.md
Generated with:
$ sed -i 's/oci-image-tools/oci-image-tool/g' $(git grep -l oci-image-tools)
Typos are from e60ff1d6 (cmd/oci-image-tool: add manuals, 2016-07-22, #180).
> oci-image-tool.1: Fix "oci-image-tools" -> "oci-image-tool" typos

- image/config.go
- image/descriptor.go
- image/manifest.go
Fix up oci-image-tool to look for hashes under `blobs/{algo}` as per https://github.com/opencontainers/image-spec/issues/208
This isn't addressing any language change required
```bash
$ tree 
.
├── blobs
│   └── sha256
│       ├── 086acbc3376eedf5a3d9c969a0d446e803600091f133288e8f5643a46e801976
│       ├── 98b338c114d348c417532b8a3bafd364f5d0c8f3541c01d0652e7c043d7d9056
│       └── bc6eb737e26b988486a6e8d5ac29167ae7aaaae7ba98fac406e4722a4eb219bb
├── oci-layout
└── refs
└── latest
3 directories, 5 files
$ oci-image-tool validate --ref latest .                                                             
.: OK # nevermind here, I just noticed it and I have plan to fix this up :) net is that tests pass
```
> image: slash separation between algo and hash

- image/manifest.go
- image/manifest_test.go
Should address the code change requested in https://github.com/opencontainers/image-spec/issues/196
/cc @philips @stevvooe @vbatts @s-urbaniak 
> image: error out on duplicate tar entry

- README.md
> [ReadMe] Remove extraneous "should"

- cmd/oci-image-tool/man/oci-image-tool-create-runtime-bundle.1.md
- cmd/oci-image-tool/man/oci-image-tool-unpack.1.md
- cmd/oci-image-tool/man/oci-image-tool-validate.1.md
- cmd/oci-image-tool/man/oci-image-tool.1.md
Taking care of https://github.com/opencontainers/image-spec/pull/180/files#r71914328
/cc @wking @philips 
> cmd/oci-image-tool/man: clarify unpack and create-runtime-bundle description

- serialization.md
On Wed, Aug 31, 2016 at 06:53:45PM -0700, Brandon Philips [wrote][1]:
> @wking I think changeset is the logical concept, layer is the
> serialization of that changeset into a tar. I really don't have a
> strong opnion about having different nouns for these things but
> @stevvooe seems to.
On Thu, Sep 01, 2016 at 10:29:16AM -0700, Stephen Day [wrote][2]:
> A "changeset" is just an english word for a set of changes. We
> represent a set of changes with a layer.
I also removed the "Image" prefix, since all of these terms are image-specific.
[1]: https://github.com/opencontainers/image-spec/pull/231#issuecomment-243954395
[2]: https://github.com/opencontainers/image-spec/pull/231#issuecomment-244151555
> serialization: Remove "changeset" from terminology

- cmd/oci-image-tool/validate.go
- image/image.go
Adds the possibility to validate multiple reference at once:
```shell
$ oci-image-tool validate --ref tag --ref 3.1 --ref 12.04 --ref latest --ref notlatest /home/amurdaca/src/github.com/docker/docker/test
reference "tag": OK
reference "3.1": OK
reference "12.04": OK
reference "latest": OK
reference "notlatest": OK
/home/amurdaca/src/github.com/docker/docker/test: OK
$ oci-image-tool validate --ref tag --ref 3.1 --ref 12.04 --ref notexists --ref latest --ref notlatest /home/amurdaca/src/github.com/docker/docker/test 
reference "tag": OK
reference "3.1": OK
reference "12.04": OK
/home/amurdaca/src/github.com/docker/docker/test: validation failed: refs/notexists: descriptor not found
```
/cc @RobDolinMS @s-urbaniak @philips @vbatts 
> cmd/oci-image-tool: support multiple --ref

- descriptor.md
Numerous grammar tweaks, simplifications through removal of some
redundant information, typo fixes, attempts to make the document more
internally consistent.
> descriptor: revamp for readability

- image/manifest.go
If there are multiple layers, it will only unpack a layer and then return.
This pr fix this.
> Fix unpack multiple layers

- cmd/oci-image-tool/man/oci-image-tool-validate.1.md
Catch up with 6ca74be5 (cmd/oci-image-tool: support multiple --ref, 2016-09-06, #265).
While I'm touching it, reformat this entry to one line per sentance per the README's [Markdown style section][1].
[1]: https://github.com/opencontainers/image-spec/tree/v0.4.0#markdown-style
> cmd/oci-image-tool/man: Document multiple --ref for 'validate'

- image/config.go
- image/descriptor.go
- image/image.go
- image/manifest.go
- schema/schema.go
- specs-go/v1/config.go
- specs-go/v1/mediatype.go
Fix https://github.com/opencontainers/image-spec/issues/260
/cc @coolljt0725 @s-urbaniak @xiekeyang
> oci-image-tool: validate descriptors MediaType

- Makefile
> Makefile: add missing document pages

- layer.md
When adding verbiage for restriction on duplicate entries in the tar
archive, it was not immediately clear where this information would be
organized.
This revamp seeks to make the document on the whole more suitable for
implementors and be interpretable for compliance.
> layer: revamp for readability

- layer.md
Fixes #220
Discussed with stevvooe, I think this makes it make sense:
```
<philips> Brandon Philips stevvooe is it a "Changeset" or a "layer"
14:53 S<stevvooe> layers represent a changeset
14:53 P<philips> Brandon Philips I feel like layer.md is trying to
discuss how layers are generated. The idea of a changeset is really part
of the image manifest.
14:54 changeset == image manifest?
https://github.com/opencontainers/image-spec/blob/master/manifest.md#example-image-manifest
14:55 S<stevvooe> well, the manifest describes the resources that make
up an image
14:55 the fact that they are changesets is an implementation detail of
the image format
14:56 P<philips> Brandon Philips Right, it just feels awkward that the
term changeset isn't really used in the manifest list where you actually
have …
```
> layer: add introductory comments

- serialization.md
I'd rather drop the field (#224), but have been unable to convince @stevvooe that there would not be side effects of that approach.  So we're back to my initial recommendation that we [require the `layers` value][2] and [require implementations to error out if they see an unknown value][3].
The use of “unknown” vs. “another” allows image and implementation authors to collaborate on additional layer types if they see a need to do so while ensuring that users not party to such extensions don't get silently-broken behavior.  This relies on extention types being suitably namespaced/unique so that two separate extension groups don't pick the same type string, but that seems like a reasonably safe bet.
The spec does not provide any way to version this field, so users wondering “is my tooling …
> serialization: Require 'layers' for rootfs.type

- manifest.md
Adding a couple links to remove confusion regarding OCI being at v1 and docker at v2 for "fat" manifest lists and distribution (image) manifests.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> adds some description re: compat with docker schemas

- descriptor.md
Bringing up discussion on layer federation..
The docker v2s2 schema also has them https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#image-manifest-field-descriptions and docker itself it's already using this feature for Windows layer.
This will allow people to implement layer federation functionality in their own registry. ISVs who want to host their layers somewhere else are now free to do so. It will be up to whatever client/server implementation to fully support them. The basic idea still remains and OCI would be fine by having this standardized.
> manifest: layer federation

- descriptor.md
- schema/defs-image.json
regular expression of algorithim in defs-image.json:
"pattern": "^[a-z0-9]+:[a-fA-F0-9]+$"
make descriptor.md consistent with it.
Signed-off-by: Deng Guangxing <dengguangxing@huawei.com>
> fix typo and regular expression of algorithim

- schema/validator.go
More types than manifest file is read by `Validator.Validate()`.
> improper error description

- image/manifest.go
- image/manifest_test.go
The media type on unpacking layer should be `MediaTypeImageLayer`
> Fix media type on unpacking layer

- descriptor.md
- schema/defs-image.json
Now that 75a51ed (fix regular expression of algorithim, 2016-08-30, #221) has made the Markdown and JSON Schema consistent (and required lowercase algorithms), make digest comparisons easier by also requiring lowercase hex.
This also:
* Makes it easier to serve blobs out of a case-insensitive filesystem
store.
* Avoids having two otherwise-identical descriptor (or
descriptor-containing) blobs with different hashes because they
picked differend hex-casing.
> descriptor: Require lowercase hex

- manifest.md
Need to be kept in-sync with: https://github.com/opencontainers/runtime-spec/pull/510
> Add some text about extensions

- layer.md
- media-types.md
Supersedes #216, Requires #169.
> layers: describe policy enforcement for foreign layer media type

- cmd/oci-image-tool/validate.go
- image/descriptor.go
- image/image.go
This is taking care of https://github.com/opencontainers/image-spec/issues/271#issuecomment-245325132 (left a TODO/FIXME for later in case).
I'll adapt everything to be same as per https://github.com/opencontainers/image-spec/issues/266 later
```shell
$ oci-image-tool validate /home/amurdaca/src/github.com/projectatomic/skopeo/busybox-oci2
reference "12.04": OK
reference "3.1": OK
reference "a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6": OK
reference "latest": OK
reference "notlatest": OK
reference "tag": OK
/home/amurdaca/src/github.com/projectatomic/skopeo/busybox-oci2: OK
```
/cc @wking @vbatts @philips @stevvooe 
> cmd/oci-image-tool: validate all refs by default

- serialization.md
> fix inline html/markdown syntax

- specs-go/v1/mediatype.go
Takes care of adding the new media type in the Go types from https://github.com/opencontainers/image-spec/pull/233 - so that can proceed and be merged w/o any other interruption.
/cc @stevvooe @philips @vbatts 
> specs-go/v1: add nondistributable media type

- README.md
71650f27 (spec: split serialization into image and layer, 2016-08-24, #206) pulled layer.md out of serialization.md, but did not update these links.
While touching the paragraph, reformat to [one sentence per line][1].
[1]: https://github.com/opencontainers/image-spec/tree/e6a431f1584468f112a52c01a02d326199b99021#markdown-style
> README: Update links after layer.md split

- image/manifest_test.go
> remove temporary directory for unit test with TestUnpackLayerDuplicateEntries

- Makefile
- README.md
- config.md
- image-layout.md
- manifest.md
- media-types.md
- schema/manifest_test.go
- schema/spec_test.go
Closes: https://github.com/opencontainers/image-spec/issues/283
> *: rename serialization.md -> config.md

- config.md
This didn't make it into #305, but I think we [still][1] [want][2] [it][3].  While I was touching headers, I shifted the informative example section down under the normative property definitions, and move the normative whitespace rule up out of the example section.
[1]: https://github.com/opencontainers/image-spec/pull/255#r77895393
[2]: https://github.com/opencontainers/image-spec/pull/305#r78646058
[3]: https://github.com/opencontainers/image-spec/pull/305#r78647317
> config: Fix "Serialization" -> "Configuration" in the title

- README.md
- layer.md
I had been unaware of formal distinctions between these terms until @stephenrwalli [called it out][1] in the context of his [suggestion to use “implementation defined” for uploading `application/vnd.oci.image.layer.nondistributable.tar+gzip`][2].  I couldn't find anything as compact as RFC 2119 around this idea, but linking to a section of the C99 rationale seems reasonable enough.  The PDF I'm linking is “Rationale for International Standard - Programming Languages - C Revision 5.10 April-2003” and the referenced content appears in section 3.
The “rationale for the C99 standard” link text seems pretty informal, but that's [what WG14 uses to refer to the document][3].
[1]: https://github.com/opencontainers/image-spec/pull/233#issuecomment-245416276
[2]: …
> README: Define "unspecified", "undefined", and "implementation-defined"

- README.md
Linking the files from Makefile's DOC_FILES in their listed order.  Link text generally follows the headers used by the linked document.  Informative stuff (for image and implementation authors) is indented under the README (although I'm [not sure there's consensus on whether `media-types.md` is normative or informative][1]).
[1]: https://github.com/opencontainers/image-spec/pull/304#issuecomment-246796088
> README: Add a table of contents

- layer.md
> layer.md: Fix some typo

- media-types.md
The Docker link landed in #55, but we've had a descriptor definition locally since #111.
> media-types: Replace Docker link with internal descriptor link

- manifest.md
Require implementations to support these media types (although an implementation which also supports additional media types is still compliant).  Suggest portable manifests and manifest lists stick to these types so the can rely on implementation support.
A manifest(-list) can safely use a type from outside the list if the author expects the implementation to support the extension type (e.g. application/vnd.docker.image.rootfs.diff.tar.gzip).  But how that out-of-band expectation is setup is beyond the scope of this specification.
Previous discussion in #286 and a few other one-off comments ;).
> manifest: List media types supported by descriptor references

- media-types.md
config.md is describe the image config json, it's not
container config JSON.
> Use 'Image config JSON' instead of `Container config JSON`

- config.md
Reformat this file to look more like manifest.md and add
OPTIONAL/REQUIRED tags on all fields.
Fixes https://github.com/opencontainers/image-spec/issues/251
> config: reformat and add optional/required

- layer.md
- media-types.md
> layer: clarify that layers are gzipped

- image-layout.md
The ref file name should be identical to tag it presents, from implementation side. And this had better to be amended in `Implementor's Note` section.
> ref file name identical to tag

- descriptor.md
We're [not][1] [forbidding][2] other OCI specs from using these fields, we're forbidding all specs (except for future versions of image-spec) from using these fields.  The wording I'm bringing in here matches what #164 landed for the `org.opencontainers.*` annotation namespace.
My personal preference would be to [use JSON-LD][3] to assign explicit semantics to every field (after which you don't have to worry about namespacing the fields themselves), but that would be a larger change ;).
Fixes #125.
[1]: https://github.com/opencontainers/image-spec/pull/111#r65460193
[2]: https://github.com/opencontainers/image-spec/pull/111#r65659259
[3]: https://github.com/opencontainers/image-spec/pull/111#r65468737
> descriptor: Rephrase reserved wording

- config.md
- image-layout.md
- layer.md
- manifest.md
This series of commits touches on the places that ordering is applied/unpacked.
Attempting to have consistent wording.
Fixes #276
> Clarify layer ordering

- config.md
- descriptor.md
- layer.md
- manifest.md
Every document that defines a media-type ought to declare the media-type
it is defining.
https://github.com/opencontainers/image-spec/pull/349#discussion_r81339429
> *: consistent media-type indications

- manifest.md
As done in #360 but missed in the just-landed #359.
Signed-off-by: W. Trevor King <wking@tremily.us>
> manifest: fix plural (media type -> media types)

- manifest.md
Change `layers[len(layers)]` to `layers[len(layers)-1]`
> 'len(layers)-1' is the top

- Makefile
Before it was just using the latest image build, which was
1.13.2-4.fc23. With this change it will more explicitly use a tagged
version.
> Makefile: update the version of pandoc

- Makefile
- README.md
- image-layout.md
- manifest-list.md
- manifest.md
- media-types.md
- schema/spec_test.go
The combined manifest/manifest-list document is long and unwieldy.
Furthermore, the Image Manifest is arguably more important (since the
Manifest List is optional), and so it should stand alone as a
first-class document.
> *: split manifest and manifest list documents

- README.md
"OpenContainer's" is plain incorrect, and "OCI" is preferable to
"OpenContainers".
> README: clean up OCI references

- README.md
- Remove redundant sentence describing media types document
- Disambiguate "OCI Layers", and more directly explain link to archival
format
- Change ROADMAP pointer to a more realistic date
- Minor tweaks to FAQ wording
> README: clean-up and clarifications

- specs-go/version.go
https://github.com/opencontainers/image-spec/milestone/8 has been cleared out.
This would be such that b472d5f is tagged as v1.0.0-rc1
> Bump version to v1.0.0-rc1

- Makefile
- README.md
- canonicalization.md
Spun off from #259, now that we seem to have reached a consensus for “SHOULD canonical JSON” there.  I've set this up so we have space to add canonicalization recommendations for other formats, although the only other basic type discussed in this repository is a gzipped tarball and that's more than I want to bite off at the moment ;).
> canonicalization: Add recommendations for canonicalization

- schema/defs-config.json
- schema/fs.go
The property had been (erroneously) "layers"; this commit fixes that by making the property "type" and using an enum to require the value to be "layers".  It also adds "required" entries for both rootfs.diff_ids and rootfs.type.
> schema/defs-config.json: Require rootfs properties and enumerate type

- config.md
This field MAY be null is duplicate with the `OPTIONAL`
> OPTIONAL field MAY be null

- layer.md
Change layer media type for consistency with `media-types.md`, add
`.v1` to layer media type.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
ping @wking , maybe you miss this one? :smile:
> Fix inconsistent layer media type

- descriptor.md
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
> Fix "a the hashs" -> "the hash" typo

- manifest-list.md
- manifest.md
> manifest(-list): Fix "object" -> "string" for mediaType

- schema/manifest_backwards_compatibility_test.go
> Use specs-go/v1 to reference media type instead of a contant string

- config.md
`arm64` image is already supported for a long time under `aarch64/` namespace on dockerhub and we 
have run docker containers for a long time on arm64.
> Add arm64 to supported architecture

- specs-go/v1/layout.go
This file found in an image-layout only had a described content, but not
a referenced structure.
> specs-go: adding structure of `oci-layout` file

- manifest-list.md
As Adrian Colley points out in #390, clients may not be aquiring the manifest over HTTP.  In most cases, folks will know (from a Content-Type header, a descriptor media type, or other means) what type of blob they're dealing with before they look at the blob.  I expect client behavior [like][2]:
> If you can verify the digest, ignore Content-Type. If you can't verify the digest,   respect the Content-Type and require it to match your expected media type (if any).
But in the absence of an HTTP-API spec I don't think we need to talk about this at all.
Fixes #390.
[1]: https://github.com/opencontainers/image-spec/issues/390
[2]: https://github.com/opencontainers/image-spec/issues/390#issuecomment-254029311
> manifest-list: Drop HTTP Content-Type sentence

- media-types.md
Fill in more generic detail for the advice which was removed in #392.
> media-types: Describe media type conflict resolution

- README.md
The 888 numbers don't seem to work; I called and it was an empty room.
> README: add correct dial in

- config.md
- manifest-list.md
The new wording makes it clear that implementations are free to support only a subset of OSes or architectures, and both implementations and blobs are free to support/use OSes and architectures not listed in runtime-spec.  Leaning on runtime-spec here lets us consolidate any OCI `GOOS`/`GOARCH` extension in a single location (runtime-spec).
Spun off from [this comment][1] in #385.
[1]: https://github.com/opencontainers/image-spec/pull/385#issuecomment-253640211
> config|manifest-list: Punt to runtime-spec for platform OS/arch

- README.md
To make it clear that supporting image-layout is optional, because there's no way to test support without requiring a particular backend (tar, HTTP, etc.).
Spun off from [here][1].
[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/s_SuN47XGC4/ycyxzzXnCAAJ
> README.md: Add high-level link to optional image-layout

- manifest.md
Point out that the layer's initial empty directory has unspecified attributes.  Layer authors interested in the ownership and other attributes of the unpacked root directory should explicitly set an entry for it.
Spun off from #318 to focus on a single point.
> manifest: Explicitly unspecified attributes for the initial layer directory

- layer.md
The existing wording was extremely confusing so this is an attempt at
clearing it up. Still not convinced this is quite right but putting it
up for feedback. Alternatively we could scrap the explanation and lean on
something like tar's:
https://www.gnu.org/software/tar/manual/html_node/Dealing-with-Old-Files.html
> layer: clarify wording around applying changesets

- config.md
`manifest digest` means the digest of manifest, I think this is wrong.
> Use layer digest in the description of DiffID

- Makefile
- README.md
To make it more readable, make `manifest.md` and `manifest-list.md` above `layer.md` and `config.md`
> Adjust the doc order of the content table

- specs-go/v1/config.go
- specs-go/v1/manifest.go
- specs-go/v1/manifest_list.go
- specs-go/versioned.go
Optional fields should be added omitempty 
> Some omitempty usage modifications

- schema/validator.go
This PR is alternate of https://github.com/opencontainers/image-tools/pull/10.
As we have some suggestion that descendants media type should be checked by JSON schema, I put up this PR.
JSON schema constrains config and layer fields type in manifest file. If this is acceptable, we should then update the vendor to this in #image-tools.
Signed-off-by: xiekeyang xiekeyang@huawei.com
> validate media type of manifest descendants

- config.md
If user doesn't know much about Dockerfile, the sentence `a command like ENV`
is confused, we should make it clear the `ENV` is an command of Dockerfile.
Singed-off-by: Lei Jitang leijitang@huawei.com
> config.md: clarify `command ENV` is an command of Dockerfile

- image-layout.md
To match the descriptor property, fixing a typo from #94, although that was developed in parallel with the descriptor spec.
> image-layout: Fix 'mediatype' -> 'mediaType' in ref payload

- config.md
based on the runtime spec, the user are platform-specific and `MemorySwap`  are for Linux based systems.
Fixed #329 
Actually, I'd like to remove `Memory` `MemorySwap` `CpuShares`
> Clarify User and MemorySwap are platform specific

- manifest-list.md
The json tag define in
https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/manifest_list.go#L34
for os.features is `os.features`, we should use
`os.features` in the example of manifest list.
> manifest-list.md: fix example

- image-layout.md
The previous wording (“has” and “contains”) was not clear enough to [avoid confusion][1].  I consider this PR to be a spec clarification, and not a spec change, but others will [probably disagree][2] (which is why I think we need the clarification).
If you cared about running images from the layout, you'd need “and there MUST be at least one unpackable ref” language.  And then you have to match the oci-layout version with the media types that were unpackable when it was current (or is validity in the eye of the validator?)…  This is a bowl that I do not want to fathom ;).
Maybe folks are just using an image-layout to ship some missing blobs (and have refs empty).  I don't see any incentive to image-authors to publish ref-less blobs and then pretend they are runnable, so I don't see a need …
> image-layout: Require blobs/refs to exist but allow them to be empty

- descriptor.md
The in-flight #431 is using JSON Schema's [`uri` format][1], which requires RFC 3986.  This commit makes that an official spec requirement by adding a MUST to the Markdown.  It also SHOULDs the http(s) schemes, because they're widely supported and are deployed in existing Docker images.  And @vbatts and @runcom both like SHOULDing them ;).
Fixes #436.
[1]: https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-7.3.6
> descriptor: MUST URIs and SHOULD http(s) for descriptor's 'urls'

- manifest-list.md
Signed-off-by: Ling FaKe lingfake@huawei.com
> manifest-list.md: fix some spelling error

- schema/fs.go
- schema/image-manifest-schema.json
- schema/manifest-list-schema.json
- schema/manifest_backwards_compatibility_test.go
For manifests and manifest lists, to match the requirements from their Markdown definitions.
> schema: Limit schemaVersion to 2 and enumerate mediaType

- config.md
the "Labels" field is not specified in the docker image spec, but is
present and used.
https://github.com/docker/docker/blob/master/image/spec/v1.2.md
This carries over that functionality
Signed-off-by: Vincent Batts vbatts@hashbangbash.com
> config: adding labels

- schema/manifest_test.go
This test case want to return failure only when `invalid` media type.
However, it lack the required fields, and will return failure whatever `mediaType` is.
So, it should be completed the accurate required fields, to make sure it to be our expectation.
> manifest test case should involve required fields

- README.md
These two sentences had been saying pretty much the same thing.  The first had previously scoped the spec to image creation, but the spec covers the format itself, creation, and unpacking.  Listing the constituent components seemed like enough for one sentence, so the new sentence stays away from format/creation/unpacking distinctions.
I've also left manifest lists out for now, since adding a reference too them seemed orthogonal do consolidating these sentences.  Adding manifest-list references is covered in #455.
> README: Consolidate "OCI Image" definitions

- specs-go/v1/layout.go
it will be used in 'image-tools' or other project for checking regular
expression of 'refs', which writes as "Object names in the refs
subdirectories MUST NOT include characters outside of the set of "A" to
"Z", "a" to "z", "0" to "9", the hyphen -, the dot ., and the underscore
_." at https://github.com/opencontainers/image-spec/blob/master/image-layout.md
Signed-off-by: Ling FaKe lingfake@huawei.com
> Add regular expression for object names in 'refs'

- config.md
- descriptor.md
- manifest-list.md
- manifest.md
Covering all cases turned up by:
$ git grep '\*array'
runtime-spec does this pretty consistently, and the first such usage appeared in image-spec with f3d0f78 (config: reformat and add optional/required, 2016-09-20, #333).  And before that, c22ca799 (serialization: docker v1 image format media type, 2016-04-04, #6) had landed some:
<code>array of strings</code>
> *: Replace '*array*' with '*array of {type}*'

- schema/fs.go
- schema/image-manifest-schema.json
- schema/manifest_test.go
Spec declares `The array MUST have the base image at index 0. `
So that we should limit it in JSON shcema, and add test case.
> limit min layer length in manifest to one

- .tool/lint
- .travis.yml
Apparently --update doesn't play nicely anymore, and has been removed
from the guidance for gometalinter usage. Let's get rid of it since it's
breaking every travis build and appears to be redundant anyway.
> travis: fix gometalinter

- manifest.md
We doesn't define a `base image`, use `base layer` is
correct. This issue first being addressed in pr #312,
and then being addressed in pr #318, and then in pr #407,
but landing #407 has a long way to go. We could address
this first to avoid confusing.
> manifest.md: use `base layer` instead of `base image`

- config.md
> lables: use `labels` instead of `annotation` in the description of labels

- schema/defs-image.json
- schema/fs.go
According to [extensibility](https://github.com/opencontainers/image-spec/blob/master/manifest-list.md#extensibility), platform object in manifest list should accept the additional properties. So the limitation of `"additionalProperties": false` should be removed.
BTW, here was a syntax error, and this limitation didn't work. Even that, it still should be removed.
> platform object should not reject additional properties

- schema/config_test.go
Test cases should contain required fields, otherwise result will be always failure whether the validated field be legal or not. That is not our expection.
And add a new test case for only required fields, to check the `optional` and `required` fields in spec.
> fix bug: config test cases MUST include all required fields

- README.md
Add language parallel to what is in the OCI Runtime.
This is a carry of #381, with fixed whitespace.
> [ReadMe] Add Compliance Language

- config.md
we doesn't define parent image in the configuration, we
should remove this sentence.
> config.md: remove "the ID of its parent image"

- image-layout.md
In real world, if you do not format the output of cat, it will be so ugly.
And the original document may generate through imagination.
Example:
```shell
[guohao@localhost image-tools]$ cat etcd-oci/
blobs/      oci-layout  refs/       
[guohao@localhost image-tools]$ cat etcd-oci/refs/latest 
{"mediaType":"application/vnd.oci.image.manifest.v1+json","digest":"sha256:99ef9268131c383a83c2845413684a66d391e98560c4a0a9ae923c5f04f79e69","size":1042}[guohao@localhost image-tools]$ cat etcd-oci/blobs/sha256/
79ac26bcdd8013a398c7b54506d25cd7c738ba061b362fd1ed56cde4d6152a26  99ef9268131c383a83c2845413684a66d391e98560c4a0a9ae923c5f04f79e69  eeee0535bf3cec7a24bff2c6e97481afa3d37e2cdeff277c57cb5cbdb2fa9e92
95e6aab6810eee8381957a8e83ddd76c5dde9d523e7cfda8f172c7b0e3e60c17 …
```
> Update image-layout.md: fix json format in practice

- .gitignore
- Makefile
- README.md
- manifest-list.md
- spec.md
Per the oci f2f at kubecon.  Similar changes what is in: https://github.com/opencontainers/runtime-spec/pull/626
> Clean-up spec to remove non-spec-ish items

- descriptor.md
> descriptor.md: Add the urls attribute instance in the Examples

- schema/defs-config.json
- schema/fs.go
- specs-go/v1/config.go
follow up https://github.com/opencontainers/image-spec/pull/371
> specs-go: add label to config.go

- specs-go/v1/layout.go
Add a ImageLayoutVersion = 1.0.0 const so implementation can
refer to rather than hard code in implementation just like
https://github.com/containers/image/blob/master/oci/layout/oci_dest.go#L173
```
if err := ioutil.WriteFile(d.ref.ociLayoutPath(), []byte(`{"imageLayoutVersion": "1.0.0"}`), 0644); err != nil {
return err
}
```
Signed-off-by: Lei Jitang leijitang@huawei.com
ping @vbatts
> Add ImageLayoutVersion const

- image-layout.md
The section for this file was too crammed together. Breaking it out into
individual items allows for more straightforward validation.
> image-layout: clarification of oci-layout

- .travis.yml
> build: upgrade to Go 1.7

- manifest.md
This got dropped somehow in commit 873b9b64fda6eed when things were
moved around in the file, so add it back.
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
> image manifest: add back 'source' annotation key

- config.md
- schema/config_test.go
- schema/defs-config.json
- schema/fs.go
- specs-go/v1/config.go
As I said in https://github.com/opencontainers/image-spec/pull/371#issuecomment-252411562,
I'd like to remove these resource limit from image-spec.
On the on hand, if we have this, we should have limit
the min and max size of these value. For example, in
docker, there are some min and max limit for some
resource, see https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L48
ping @vbatts  @stevvooe 
> Remove Memory MemorySwap CpuShares from config

- spec.md
This landed in #432 but was removed in #458, likely accidentally during a rebase.
> spec: Restore compliance language

- config.md
> fix json format of example in config.md

- image-layout.md
Signed-off-by: Vincent Batts vbatts@hashbangbash.com
> image-layout: organize for anchors

- glide.lock
- glide.yaml
- identity/chainid.go
- identity/chainid_test.go
- identity/helpers.go
- vendor/github.com/opencontainers/go-digest/LICENSE.code
- vendor/github.com/opencontainers/go-digest/LICENSE.docs
- vendor/github.com/opencontainers/go-digest/algorithm.go
- vendor/github.com/opencontainers/go-digest/digest.go
- vendor/github.com/opencontainers/go-digest/digester.go
- vendor/github.com/opencontainers/go-digest/doc.go
- vendor/github.com/opencontainers/go-digest/verifiers.go
- vendor/github.com/pkg/errors/errors.go
The specification defines an algorithm to calculate a `ChainID`, which
can be used to identify the result of subsequent applications of layers.
Because this algorithm is subtle and only needs to implemented in a
single place, we provide a reference implementation.
For convenience, we provide functions that calculate all the chain ids
and just the top-level one. It is is integrated with the
distribution/digest type for safety and convenience.
As part of this, the `identity` package has been introduced. For
consuming code, a few helpers have been provide to ease transition as
the name of the upstream package has not yet been finalized. Users of
this package should employ `FromBytes`, `FromString` and `FromReader`
where appropriate, which should ease the transition if these packages
change. …
> identity: add implementation of ChainID

- Makefile
This fixes the `glide-vc` command to use the glide.lock file to resolve
the dependencies, ensuring that we don't delete test dependencies. We
also fix a sed line to working correctly on other platforms as well
ensure that the tools get updated.
> Makefile: address problems with updating deps

- layer.md
Attempt to clarify when non-distributable policies should be enforced
(only on upload, never on download); as discussed in + fixes #475
> layer: wordsmith non-distributable section

- schema/manifest_backwards_compatibility_test.go
When I execute the test command, I get the following warning, so I made the following changes.
`$ go test`
`warning: config sha256:5359a4f250650c20227055957e353e8f8a74152f35fe36f00b6b1f9fc19c8861 has an unknown media type: application/octet-stream`
> Modify the test's config type

- README.md
The links help with discoverability, otherwise folks reading the README might not notice that we provided these resources in addition to the spec itself.
The Go-compat policy formalizes the rough sketch [here][1].  By declaring a Go-compat policy, folks who have Go troubles can tell without testing whether the image-spec tooling *should* work for their Go environment.  And if/when it does not, they can see whether image-spec is interested in patches or not.  For example, if the tooling breaks on Go 1.5, we don't care or want some awkward workaround.  But if it breaks on Go 1.6 we do care and want a patch.   And if someone wants to genericize our test suite to run on both 1.6 and 1.7, we want a patch for that too.
And I'm just guessing at 1.6.  Maybe the repo-policy is to support 1.5+? …
> README: Link to specs-go and schema and declare Go-compat policy

- spec.md
> spec.md: add some description about manifest list

- image-layout.md
- manifest-list.md
- manifest.md
- schema/image-manifest-schema.json
- schema/manifest-list-schema.json
- specs-go/v1/config.go
- specs-go/v1/descriptor.go
- specs-go/v1/manifest.go
- specs-go/v1/manifest_list.go
- specs-go/versioned.go
Due to the conflicting use of the `mediatType` field across                                   
documents, and after discussion on                                                          
https://github.com/opencontainers/image-spec/pull/411,                                                
this changeset removes the use of `mediaType` where it is used to refers                                                     
to a document's own type. Leaving only the use of `mediaType` for                                      
descriptors, where it is used to describe the type of a referenced object.
> specs-go: clarify mediatypes

- specs-go/v1/descriptor.go
cc @opencontainers/image-spec-maintainers
> specs-go/v1: use digest type on descriptor

- .travis.yml
- Makefile
Only use the auto-ranging when Travis tells us what the range is.  Use our `EPOCH_TEST_COMMIT`-based range in all other cases.
This may fix the issue we've been having with #514.
> Makefile: Use 'ifdef TRAVIS_COMMIT_RANGE' for git-validation

- Makefile
- annotations.md
- descriptor.md
- manifest-list.md
- manifest.md
- spec.md
this has come up in discussion and is needed for adding discoverable arbitrary data to the descriptor references. Especially in making an index for image layout.
In DRY'ing up the references to annotations. This makes the defined keys in a very logical place rather than the bottom of one of the other docs.
> Descriptor annotations

- schema/content-descriptor.json
- schema/defs-image.json
- schema/fs.go
- schema/manifest_test.go
- schema/manifestlist_test.go
Validate manifest list JSON object via schema.Validator.
* To validate full fields;
* To validate required fields only;
* To validate customized reference manifest media type;
* To validate invalid media type case;
* To validate invalid field type case;
> Bug Fix: error syntax in schema definitions

- Makefile
- considerations.md
- manifest-list.md
- manifest.md
- spec.md
[As][1] [I][2] [suggested][3] in #164.
The extensibility requirements might arguably apply to our other JSON types as well (like annotations, which were recently DRYed up in #501).  The new extensibility section sets the stage for that, but I've left the other types off this commit to focus on making the current requirements more DRY without changing the specified behavior.
My personal preference would be to have separate `canonicalization.md` and a (very short) `extensibility.md` file, but @jonboulle [wanted the single file][4].
This PR is a resubmission of #340 after rebasing around the just-landed #501 (as [requested][5] by @stevvooe).
[1]: https://github.com/opencontainers/image-spec/pull/164#issuecomment-243952187
[2]: https://github.com/opencontainers/image-spec/pull/164#issuecomment …
> considerations: DRY extensibility

- image-layout.md
should not be present 2 identicial cas file under a dir.
> fix repeated content address example

- config.md
@stevvooe and I [couldn't agree on more detailed wording][1], and this paragraph was never normative anyway.
Spun off from #388 starting [here][2].  The new wording does not mention media types at all, so there's no reason to tangle it up with the rest of #388.
CC @stevvooe.
[1]: https://github.com/opencontainers/image-spec/pull/388#discussion_r96765401
[2]: https://github.com/opencontainers/image-spec/pull/388/files#r96978832
> config: Simplify the paragraph contrasting diffIDs with layer digests

- schema/manifest_backwards_compatibility_test.go
> compatibility_test.go:change manifest to manifestlist

- config.md
- specs-go/v1/config.go
This brings us into compliance with JSON Schema, whose [current validation draft requires RFC 3339 for date-times][1].  I've modeled the reference phrasing on the draft JSON Schema's date-time definition.
Fixes #389.
Obsoletes #480 (which still hasn't grown a Signed-off-by).
[1]: https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-7.3.1
> config: Require RFC 3339's more restricted version of ISO 8601

- image-layout.md
The image spec shouldn't reference real names/addresses in example
content. Switch to the same fake one we use elsewhere. It's like
alternative facts.
> image-layout: use a made-up name/email for author

- specs-go/v1/config.go
Modify History.Created and Image.Created to be of type time.Time so that creation times may be validated, compared, etc.
> specs-go: Image.Created uses a string type

- image-layout.md
A ref → descriptor example caption gained “blobs the manifest references” wording with 2f24791, #136, but I don't see a direct relationship between descriptors and those deeper-ancestor blobs.  I think we either want to revert the changes 2f24791 made to this line or drop the line.  In this commit I drop the line, because the other points covered by the sentence are already covered in other descriptor docs.  And it's pretty clear just from the example command and output that this is showing the content of a ref pointing at a manifest list.
Fixes #427.
> image-layout: Drop manifest ref example description

- HACKING.md
Updating Go version dependency
The prerequisites in HACKING.md states Go >= 1.5 is supported. 
However, the tests will not pass in 1.5 or 1.6, nor will the linting as
testing.T.Run() which is used was added in Go 1.7. 
This patch updates the prerequisite to the latest Go version. A  
specific version is not specified as this will likely have to be 
changed repeatedly in the future. But it does remove the incorrect
version with some guidance to upgrade.
Fix #535 
Signed-off-by: David Lyle david.lyle@intel.com
> Fix prerequisites in HACKING

- schema/manifest_backwards_compatibility_test.go
This fix changes the manual assembly of the digest (sha256) in `schema/manifest_backwards_compatibility_test.go`, as `go-digest` is already in place in github.com/opencontainers.
This fix fixes #513.
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> Use go-digest to replace manual assembly of the digest

- descriptor.md
- schema/descriptor_test.go
Cherry-picking the $ref fix from #444, since there was a lot going on
in that PR around the manifest list.  Fixing those things is good, but
I thought it would help review to have something that just focused on
descriptor bugs.
CC @xiekeyang.
> schema: Add descriptor tests and fix mediaType pattern

- README.md
The oci-scope-table moved from governance/ to about/
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> fixes broken links to oci-scope-table

- image-layout.md
- specs-go/v1/layout.go
Two minor fixups in the wake of #533.  Details in the commit messages (which I'm happy to split out into separate PRs if folks want).
> *: Catch up with refs/ removal (remove RefsRegexp, etc.)

- spec.md
Closes #409 
Obsoletes #497 
cc @RobDolinMS @philips
> Carry pr497

- manifest-list.md
PR #533 removed annotations by accident. (489e00e specifically).
This adds that definition back.
> manifest-list: add back annotations

- schema/config_test.go
- schema/descriptor_test.go
- schema/manifest_backwards_compatibility_test.go
- schema/manifest_test.go
- schema/manifestlist_test.go
- schema/schema.go
- schema/validator.go
- specs-go/v1/layout.go
We had added image layout schema, but didn't add image layout validator.
Add imagelayout validator and ImageLayoutFile const, so image tool and other
tools can use image -spec to validate the layout of the oci image.
> Add imagelayout validator and ImageLayoutFile const

- specs-go/v1/descriptor.go
@opencontainers/image-spec-maintainers  PTAL
> specs-go/v1: add annotations field to descriptor

- Makefile
I like that there is a "help" target, but the default ought to do
sensible things. :-)
> Makefile: suitable "default" target

- image-layout.md
> image-layout: Fix "auxilary" -> "auxiliary" typo

- schema/validator.go
According to [this](https://github.com/opencontainers/image-spec/blame/master/manifest.md#L57-60)  modified.
> validate.go: add the verification content

- config.md
- schema/config-schema.json
- schema/config_test.go
- specs-go/v1/config.go
Close #541 
@stevvooe @vbatts PTAL I probably forgot something
> config: add StopSignal

- descriptor.md
Before this commit, there wasn't something obvious to point to if you wanted to explain the `sha256` identifier.
The “SHOULD be submitted” wording follows [runtime-spec's example][1].
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc4/config.md#platform
> descriptor: Define the 'sha256' algo identifier

- schema/backwards_compatibility_test.go
Catch up with #388.  I think this PR and #548 are all we missed in #388.
> schema/manifest_backwards_compatibility_test: Fix gzip compat type

- specs-go/v1/index.go
We are already working with images, so we don't need to repeat
ourselves. Changing `ImageIndex` to `Index.
> specs-go/v1: remove stutter in name of index

- config.md
Closes #482.
cc @dmcgowan @opencontainers/image-spec-maintainers
> config: provide more complete explanation of ChainID

- schema/defs-image.json
The `null` option has been in the JSON Schema since #44, although I expect it was accidental.  The spec has clearly not allowed:
"annotations": null
since #164 landed with the following (still current) requirements:
> Annotations MUST be a key-value map where both the key and value MUST be strings.
and:
> If there are no annotations then this property MUST either be absent or be an empty map.
Folks without annotations should not set the property at all, or they should set it to:
"annotations": {}
> schema/defs-image: Remove 'null' from valid annotations

- schema/imageindex_test.go
> manifestlist_test: fix test

- Makefile
With #586 there are math spec characters introduced. This required a few
new latex packages and specifying xelatex.
Fixes #596
> Makefile: newer pandoc and fancy xelatex (FIXES MASTER)

- schema/gen.go
To avoid accidentally including [`.swp`, `.un~`, etc.][1]  Test with:
$ touch schema/.defs-image.json.swp
$ touch schema/.content-descriptor.json.un~
$ touch schema/foojson
$ make schema-fs
$ grep '"/' schema/fs.go
"/config-schema.json": {
"/content-descriptor.json": {
"/defs-config.json": {
"/defs-image.json": {
"/defs.json": {
"/image-layout-schema.json": {
"/image-manifest-schema.json": {
"/manifest-list-schema.json": {
"/": {
local: "/",
CC @vbatts.
[1]: https://github.com/opencontainers/image-spec/pull/533#discussion_r98296739
> schema/gen: Include .json instead of excluding .go

- .gitignore
- .tool/genheader.go
- Makefile
Fixes #247
Fixes #435
this makes an ephemeral header that gets included into the html doc that
bases the images path to pull from the same tag on github.
CC @RobDolinMS @wking 
> docs: image base reference

- Makefile
So we can make `schema/fs.go` in Travis.
This pulls a commit out of #530, but we'll want this whether we take the #530 approach or @vbatts approach from #533.  Missing this commit doesn't cause an error in the #533 tests at the moment, because the current tip is [not actually rebuilting `fs.go`][1].
[1]: https://github.com/opencontainers/image-spec/pull/533#discussion_r98332378
> Makefile: Add .install.esc and make it part of install.tools

- layer.md
Avoiding [this][1]:
pandoc: Duplicate link reference `[rfc1952]' "source" (line 1044, column 1)
which is breaking current master builds.  More on this (and the solution I'm using here) [here][2].
[1]: https://travis-ci.org/opencontainers/image-spec/builds/209076959#L363
[2]: https://github.com/opencontainers/runtime-spec/blob/dd41d8ffd6dd29fc0be1f3197519f11727cb19d3/style.md#links
> layer: Use rfc1952_2 as a link reference

- schema/descriptor_test.go
To mirror the invalid entry added in #580.
> schema/descriptor_test: Add test with a valid entry in 'urls'

- Makefile
- implementations.md
> implementations: add a list of known implementations

- image-layout.md
In layout.md, The validated target should be image layout itself, not only image index.
I'd like to extract and land this firstly, while #452 is in WIP. 
> fix error valid target in image-layout

- specs-go/v1/index.go
> index.go: add omitempty to platform

- annotations.md
- config.md
- image-layout.md
> spec: namespace annotations defined in image spec

- schema/image-layout-schema.json
https://github.com/opencontainers/image-spec/pull/579#issuecomment-285132348
> schema: slight clarification for oci-layout file

- config.md
The DiffID exploration doesn't parse as cleanly as it could to me and I'd like
to work on improving it. Starting with some hopefully uncontroversial tweaks.
> config: minor cleanup

- config.md
- image-layout.md
The capslock changes speak for themselves. I tried to avoid situations where deliberately capitalizing SHOULD were too prescriptive.
As for the s/should/MUST/, I think it's appropriate here as there will never be a situation where aborting on invalid keys is a thing that is allowed. I hope you agree that this is an appropriate change.
Thanks!
> s/should/SHOULD/ in a few spots, also a s/should/must/

- config.md
As noted in
https://github.com/opencontainers/image-spec/pull/608#discussion_r105802346 , we shouldn't be mandating that implementers use something like
tar-split to facilitate reproducible DiffIDs, but rather recommend it.
> config: change reproducibility "MUST" to "SHOULD"

- README.md
> README: trim faq and point to the main site

- annotations.md
- config.md
- considerations.md
- descriptor.md
- image-layout.md
- layer.md
Hope this is a welcome change. Thanks!
> use a bulleted list for rules in many places

- .tool/lint
- image-layout.md
- media-types.md
- schema/schema.go
- specs-go/v1/mediatype.go
Following #579.
To add a new specific media type for oci-layout, serving over its transportation.
> define media type for oci-layout

- .pullapprove.yml
Pull in changes from opencontainers/project-template#29.  The only changes vs. the upstream version are:
* Kept the image-spec-specific `approve_regexp`.
* Removed all the groups except for the image-spec group.
After this PR lands, PullApprove will start treating @jbouzane's [review][1]-[approvals][2] as LGTM votes.
[1]: https://github.com/opencontainers/image-spec/pull/567#pullrequestreview-25901352
[2]: https://github.com/opencontainers/image-spec/pull/609#pullrequestreview-27199819
> .pullapprove.yml: Switch to v2 and other project-template updates

- specs-go/v1/config.go
> specs-go/v1: use correct field type for diff ids

- Makefile
found that the the `/` redundant, and makes the path `/header.html` for local pandoc builds.
> Makefile: fix src path for local pandoc builds

- specs-go/v1/config.go
This field was not similar to the other fields and causes problems when dealing with using this struct to convert between docker v1 and oci v1 repositories (I cheat a little by doing this, I realize it's not a long term solution).
Still, this seems out of place and I wanted to fix it while I noticed.
> specs-go/v1/config.go: Capitalize `Labels`

- config.md
> config.md: Sentence modification 

- specs-go/v1/config.go
PR #534 changed Created from string to time.Time field.
This neutered the `omitempty` property on it, as a missing
field is now populated as the default time.Time value.
This commit turns the field into a pointer, in order to keep
the empty-value semantic for `omitempty`.
Fixes https://github.com/opencontainers/image-spec/issues/626
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>
> specs-go/v1/config: pointer-ify optional "Created" field

- specs-go/v1/index.go
The spec states that platform is an optional field for the items in the
image index. Pull request #607 added omitempty to the field, but
omitempty only works for types with a zero value. Because Platform is a
struct, it will never be omitted. The platform field should instead be a
pointer so that it can be properly omitted when it has no value.
Currently, serializing an index.json without populating platform leads to
something like the following:
```
{
"schemaVersion": 2,
"manifests": [
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"digest":
"sha256:d73e0d70cb05a373b5a666ba608139624d90a88d0155d2ade06a6001a27cd8d5",
"size": 348,
"platform": {
"architecture": "",
"os": ""
}
}
]
}
```
With the change in this patch, leaving platform as nil will cause it to
be omitted as …
> Make the Platform field actually optional.

- specs-go/v1/manifest.go
> Fix "manifest list" typos for manifest annotations

- specs-go/v1/descriptor.go
- specs-go/v1/index.go
Unifying the descriptor type makes it much easier to handler descriptors
in generic manner. This change ensures that a single deserialization can
be done a descriptor that may be processed in separate contexts.
It is unclear whether or not the specification should be pedantic about
this, as well. As it is written, these fields are only valid when being
referred through a manifest, but this distinction is only required
during validation. It may be possible to lift the platform definition to
the descriptor type, but this isn't strictly necessary.
Addresses #588.
Closes #618.
> specs-go/v1: unify the descriptor type

- considerations.md
I felt the linking of the word `are` and `content-addressible` to foreign topics unrelated to the words needed to be changed to be more explicit. I hope you agree.
Thanks!
> considerations.md: use clearer links to describe concepts

- README.md
- spec.md
This replaces the inline links with a bulleted list that clearly states each part of the spec and a little blurb that describes it. I think it's a much easier way to navigate, I hope you agree.
I also made the README link to the spec a lot more prominent.
> README: rework description of spec components

- config.md
from
https://github.com/opencontainers/image-spec/pull/635#issuecomment-291634824
it was clear that all the rules for `Labels` are the same as
annotations, so let's DRY that up a bit.
> config: DRY up labels with annotations reference

- README.md
@RobDolinMS had been keeping the wiki up to date with links to the MeetBot logs, but linking directly to the MeetBot logs gives us one less thing to maintain.  The meetings which are only in the wiki are 2015-07-22, 2015-08-05, 2015-08-12, 2015-08-26, 2015-09-02, 2015-09-09, 2015-09-16, 2015-09-24, 2015-09-30.  The last is in MeetBot, but it was our first MeetBot meeting, so the MeetBot logs are not great.  However, *all* of those meetings predate image-spec ([founded
2016-03-24][1]), so I haven't bothered to link the runtime wiki at all.
This PR cherry-picks and adjusts opencontainers/runtime-spec#739 now that it has landed in runtime-spec.
[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/tob/KGyPpu8YfNk
> README: Link to MeetBot logs for meeting minutes

- config.md
While the other annotations references (e.g. [here][1]) use the “This OPTIONAL property…” pattern, `config.md` puts the OPTIONAL/REQUIRED-ness [in the same line as the property name][2] (while [`manifest.md` does not][3]).  My preferred larger fix would be to follow runtime-spec and consistently declare OPTIONAL/REQUIRED-ness in the same line as the property name, but that's a bigger change.  This commit just removes the redundant OPTIONAL from the description body.
Spun off from [here][4].
[1]: https://github.com/opencontainers/image-spec/blame/v1.0.0-rc5/manifest.md#L69
[2]: https://github.com/opencontainers/image-spec/blame/v1.0.0-rc5/config.md#L117
[3]: https://github.com/opencontainers/image-spec/blame/v1.0.0-rc5/manifest.md#L66
[4]: …
> config: Remove redundant OPTIONAL from Labels description

- spec.md
Chasing #621, standardise on case/punctuation/articles
> spec: consistent wording

- spec.md
Fixing overly-strict wording from #641 (see [this comment][1]).  We [explicitly allow `manifests` to be empty][2], which allows you to do things like distribute an image-layout which only provides CAS blobs.
[1]: https://github.com/opencontainers/image-spec/pull/641#discussion_r110429162
[2]: https://github.com/opencontainers/image-spec/blame/eb02c88ef382324a1572fa8c66f836a00d865a3f/image-index.md#L26
> spec: Drop "one or more" from index description

- image-index.md
- image-layout.md
`base properties` is not quite clear because we don't
define which property is the base properties and which
is not the base properties. Use `REQUIRED properties`
to make it more clear.
> Use `REQUIRED properties` instead of `base properties`

- image-index.md
We are repeating the REQUIRED statement here in image-index.md which is properly located in the forward reference document descriptor.md. All upper case terms hold special meaning see  https://tools.ietf.org/html/rfc2119
Additionally as @wking points out, we're also including OPTIONAL descriptor properties in the extension, not just the REQUIRED properties.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> address duplicate REQUIREMENT

- media-types.md
- spec.md
> Drop "one or more" from index description, follow up #644

- annotations.md
Other label schema projects include the following items that are not yet
included in OCI Images. This PR adds support for `version`, `vendor` and
`revision` to bring parity to OCI defined image labels.
> annotations.md: added useful annotations

- image-index.md
It should be clarified that the manifest is describing what is
'in the image', not what 'it will run on'.
Signed-off-by: Matt Spencer <matt.spencer@arm.com>
> Platform identifies the image runtime requirements

- .tool/lint
CI has been flaky for the too short deadline (https://github.com/opencontainers/image-spec/pull/650#issuecomment-296584432)
60s might be extremely long, but I think it does not hurt.
> .tool/lint: increase deadline

- descriptor.md
As previously discussed in #589, implementations may wish to use SHA-512 for
performance/security reasons, and since our endorsed digest package also
supports it, let's add the algorithm identifier to the recognised ones in the
spec.
At the same time, we keep wording to clarify (and indeed mandate) that SHA-256
MUST be supported by implementations and is preferred for interoperability
reasons.
> descriptor: recognise sha512, tweak wording

- descriptor.md
Signed-off-by: Qian Zhang <zhq527725@gmail.com>
> descriptor.md: add descriptions for the extended field

- annotations.md
By restricting the scope of the annotation
`org.opencontainers.image.ref.name` to only image indexes appearing in
the context of an image layout, we can greatly simplify processing and
selection of target content. While other properties may apply down, we
ensure that naming is restricted to a single "entity", the `index.json`,
ambiguity for a given reference is reduced.
This does not apply to other annotations, which may "apply downward" to
other resources referenced. The application of annotation downward is
specific to a particular annotation.
Related to #588.
> image-layout.md, annotations.md: restrict scope of ref.name

- config.md
double quotes are not necessary when setting env value
> config.md: small fixes

- config.md
> config.md: typo and sentence fix

- descriptor.md
Avoid adding a second word meaning the same thing (spun off from [here][1]).  I've consolidated around “registered” because it matches the existing “Registered algorithms” header.
Also some copy-edits for the sentences I've touched:
* “alpha numeric” -> “alphanumerics” (matching [Wikipedia][2]).
* “paramterize” -> “parameterize”
* “future extension of digest support” -> “extensions”, because folks may be taking advantage of the extended grammar *now*, without waiting for the image-spec to take advantage of the extended grammar.
[1]: https://github.com/opencontainers/image-spec/pull/654#discussion_r114640550
[2]: https://en.wikipedia.org/wiki/Alphanumeric
> descriptor: Replace "supported" with "registered"

- descriptor.md
- schema/descriptor_test.go
- schema/validator.go
Disallowing upper characters will be useful for avoiding implementation bugs
> descriptor: sha{256,512}: disallow /[A-F]/ characters

- HACKING.md
- schema/schema.go
> replace file system with filesystem to keep consistent

- image-index.md
- schema/backwards_compatibility_test.go
- specs-go/v1/descriptor.go
Please refer to https://github.com/opencontainers/image-spec/pull/632 for previous discussion.
In this PR, I avoided to use Linux-specific uname values for ease of porting to non-Linux.
https://github.com/opencontainers/image-spec/pull/632#discussion_r109226040
> image-index: define platform.variant for arm

- annotations.md
Provided a conversion table to describe the equivalent values between
label-schema.org and OCI image annotations. Some values are clarified.
The human-readable `name` and `description` have also been added.
> annotations.md: label schema compatibility table

- image-layout.md
Following sentences were conflicting:
* A blob, referenced with digest `<alg>:<hex>` (per [descriptor](descriptor.md#digests-and-verification)), MUST have its content stored in a file under `blobs/<alg>/<hex>`.
* The blobs directory MAY be missing referenced blobs, in which case the missing blobs SHOULD be fulfilled by an external blob store.
> image-layout: fix inconsistent description about external blob store

- annotations.md
From: https://github.com/opencontainers/image-spec/issues/658#issuecomment-301494825
* Source is not just to binaries.
* the strings already say URL, so it's redundant
* git:// is a valid URL as well
> annotations: addressing comments

- annotations.md
Instead of comma-separated short identifiers, which have unclear semantics (are the delimiters `AND` or `OR`?).  I don't see any discussion of the syntax for this field in #636 (which landed it), but I'd floaded license expressions before in the sub-thread starting [here][2].  @gregkh had pushed back against my earlier proposal (licensing information on descriptors) [with][3]:
> No, that's not going to work at all, you can't properly describe the license for a whole layer in any form of a string that could be standardized or parsed. SPDX is great for describing the individual licenses of things, but not for a collection of things, which almost always has an arbitrary license (example, what's the license, in a simple string, for a Ubuntu base layer?)
But SPDX License Expressions are both …
> annotations: Use SPDX License Expressions for licenses

- image-index.md
- schema/backwards_compatibility_test.go
- schema/fs.go
- schema/image-index-schema.json
- schema/imageindex_test.go
- specs-go/v1/descriptor.go
While the intended use of the `platform.features` field was to express
the availability of hardware instructions on CPUs, the practicality of
expressing and implementing such a standard has been called into
question. Much of the functionality is usually hidden deep within kernel
code or is defined by hardware vendors in ways that will make the field
unusable without future additions. Applications that can make use of such
field will likely have other requirements on top of this field that are
specific to a deployment.
In that regard, it is best to remove this field and defer to hardware to
make the decision about what can be run.
Closes #622
> image-index: remove platform.features field

- image-index.md
- specs-go/v1/descriptor.go
Please refer to #632 for previous discussion.
> image-index: define platform.os.version on Windows

- spec.md
MUST NOT and SHALL NOT means an absolute prohibition of the spec. They should be one of requirements to judge one implementation if it is compliant.
> Add MUST NOT and SHALL NOT to conventions

- schema/validator.go
Fixes opencontainers/image-tools#39
reopen #469 
> schema: add checkPlatform

- Makefile
- conversion.md
- manifest.md
Add documentation about how to convert from an OCI image configuration
to an OCI runtime configuration. In particular, describe precisely what
fields need to be filled given a particular configuration.
The fields have been grouped into several categories, because some of
the image fields are not as well-thought-out as others (such as the
resource limitation fields, which should really be decided by the user
not by the image creator). In addition, some fields (such as Volumes)
cannot be understood by a generic configuration converter.
Fixes: #479
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> conversion: add document about image -> runtime configuration

- annotations.md
- specs-go/v1/annotations.go
> specs-go: add const for annotation keys

- conversion.md
Reference: https://github.com/opencontainers/image-spec/pull/492#issuecomment-305273976
> conversion: follow-up touch-ups

- annotations.md
Started from the URI charset, and ended up with a broader set and pattern from the docker tag. While not strictly the same, it's closer to the ideal set for containerd, flatpak and others.
Fixes #599
> annotations: restrict character set of ref.name values

- schema/validator.go
It's covered this since opencontainers/go-digest#34, so we don't need to do it locally.  Also, use a more specific check for ignoring unrecognized algorithms, because we don't want to return nil when go-digest notices an invalid encoding, etc.
This fixes issues like [this][1]:
-- FAIL: TestDescriptor (0.09s)
descriptor_test.go:300: test 14: expected validation failure true but got false, err <nil>
which have been affecting recent unit tests on unrelated PRs.
[1]: https://travis-ci.org/opencontainers/image-spec/builds/241019584#L373
> schema/validator: Punt sha256/sha512 hex-validation to go-digest

- config.md
- conversion.md
- image-index.md
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>
> Change platform ref from runtime-spec

- Makefile
Since READLINK(1) varies across platforms, namely darwin version does
not have the `-f` flag, then don't rely on the shell. Especially since
gnu make already has this as a builtin function.
> Makefile: use make builtin rather than shell

- annotations.md
- considerations.md
- descriptor.md
To clarify the grammar definitions, we define the subset of EBNF used by
this specification to specify various field formats.
Closes #692
> spec: describe components of EBNF grammar

- schema/config_test.go
- schema/validator.go
Related: https://github.com/moby/moby/pull/33557
> schema/config_test.go: add a test for an env var without `=value`

- config.md
- conversion.md
- specs-go/v1/config.go
Relaxes the specification of `Config.Volumes` by avoiding references to
the concept of "data volumes". Implementors are merely instructed to
provide mounts outside the container's root filesystem.
Closes #687
Supersedes #504
cc @vbatts @cyphar
> config: relax specification of Config.Volumes

- spec.md
> spec: add conversion references

- image-index.md
Please refer to #632 for previous discussion.
> image-index: define platform.os.features on Windows

- layer.md
As I mentioned in #415, some file types (sockets, block devices, character devices, FIFOs) are not currently supported on Windows. This change intends to clarify that not all file types are supported on all platforms without being too prescriptive.
> layer: clarify that not all file types need be supported

- layer.md
Windows relies on additional file attributes to produce a working image. This change documents the encoding of the necessary fields (which seems particularly important because these vendor-specific extensions are not currently documented anywhere else).
> layer: document Windows-specific file attributes

- conversion.md
- image-layout.md
Despite this not being a valid link, until the runtime spec has its
v1.0.0 release, these URLs need to be accurate for once the this spec is
tagged v1.0.0
Part of #615 
> *: update runtime-spec links to v1.0.0

- specs-go/version.go
Vote for this release: https://groups.google.com/a/opencontainers.org/d/msg/dev/5uVsyNyPhvc/G6s4afXGBQAJ
No changes sense rc7 tag
> Release v1.0.0

- image-layout.md
- manifest.md
sha256:e6924... had been used for both manifest and tar layer.
We should use different digest values for different kind of examples.
> avoid using same digest for different kind of examples

- implementations.md
[docker2oci](https://github.com/coolljt0725/docker2oci) is a cli tool to convert a image saved from
`docker save` to oci format image.
It's kind of implementation of oci image format, it's a very
convenient tool to get a oci image. If you are interested,
I'd like add this to implementations.
```
$ docker save -o busybox.tar busybox
$ docker2oci -i busybox.tar busybox
```
or
```
$ docker save busybox | docker2oci busybox
```
Check the the image:
```
$ find busybox -type f
busybox/blobs/sha256/8baf43d43a34a0e6649c254b0200c2406fc40a501a852ba51a86ac3672dc0441
busybox/blobs/sha256/40a114053d955a2b80ee2cf6e13410b28b59594ceee9036b41e12c42d3e16615
busybox/blobs/sha256/8ac8bfaff55af948c796026ee867448c5b5b5d9dd3549f4006d9759b25d4a893
busybox/index.json
busybox/oci-layout
$ oci-image-tool validate …
```
> Add docker2oci to implementations

- image-layout.md
Adjusting wording we've been carrying since #605.
On Windows, an unpacked layout will use backslashes.  Layouts really don't care what the directory separator is, and each access method (filesytem access, tar unpacker, etc.) already has an unambiguous separator character.
This is a very minor nit, but seems easy enough to clean up.
> image-layout: Replace "slash separated layout" with "directory structure"

- .travis.yml
Locally this fixes lint failure (#735), but not sure why (sorry cargo-cult)
> travis: use Go 1.9

- conversion.md
In b6d5a8cc1562 ("Change platform ref from runtime-spec"), the
conversion to runtime-spec for the "os" and "architecture" fields was
removed (as the fields had also been removed in runtime-spec). Re-add
the conversion as an annotation field rather than a verbatim field.
[Obviously this can't go into `1.0.0` due to the time window, but we can put it in `1.0.1`].
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> conversion: add platform conversions

- schema/content-descriptor.json
- schema/defs-descriptor.json
- schema/fs.go
- schema/schema.go
The `"id"` values in JSON schema files must be unique, per RFC draft 8.3.1:
> A schema MAY (and likely will) have multiple URIs, but there is no way for a URI to identify more than one schema.
and recent `gojsonschema` fails when handling such inputs (fairly nontransparently, it silently fails to resolve `$ref` references to absolute URIs and reports something like
> Reference defs.json#/definitions/mapStringString must be canonical
.  This is visible in `make test`.)
In particular, the `https://opencontainers.org/schema/image/descriptor/annotations` `id` value had three definitions.  To resolve this:
- Leave the definition in `image-index-schema.json`; although using the `/descriptor` subnamespace for the `"manifests"` array is a bit surprising, the `/image/` part clearly belongs to …
> Fix duplicate "id" values in JSON schema

- Makefile
> Makefile: variable cleanup and creation

- image-index.md
- manifest.md
As per out discussions on the dev mailing list, this is the first step towards ensuring that storage and distribution of non-specified content can be experimented with while maintaining a standards-compliant registry.
cc @stevvooe
> Unspecified descriptor mediatypes MUST be ignored

- annotations.md
Fixed a small typo in the header of the table comparing `org.opencontainers.image` and `org.label-schema` prefix.
> Fixed a small typo

- annotations.md
Move "prefix" to out of the code backtick.
> Fix table header grammar in annotations

- README.md
Point to one canonical location for meeting details, frequency, minutes,
agenda, etc.
Closes: #779 
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>
> Reference "org" repo for meeting info

- layer.md
- media-types.md
Closes: https://github.com/opencontainers/image-spec/issues/787
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> media-types: Define layer media types suffix '+zstd'

- schema/validator.go
- specs-go/v1/mediatype.go
Add go constants for the zstd MIME types to make them usable by
consumers of the go package.
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>
Cc: @giuseppe, @vbatts, @cyphar, @rhatdan, @AkihiroSuda, @jonboulle
> zstd: add constants to specs-go/v1

- schema/manifest_test.go
This is another thing I noticed this morning - the mediatype for layers should be in the layers family, but there were two tests (checking for other things) that had config types instead. Should this have been caught, or given that the tests were for failures for other things, it would have been caught had those other things not been wrong?
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
> Mediatype of layers should be application/vnd.oci.image.layer.v1.tar+gz

- MAINTAINERS
Switch approved by Jason Bouzane via email to OCI TOB mailing list: https://groups.google.com/a/opencontainers.org/g/tob/c/Q08hiintwY4/m/tMreB9LgCwAJ
Text:
```
From: Jason Bouzane <jbouzane@google.com>
Date: Thu, 25 Mar 2021 11:34:51 -0600
Message-ID: <CAFi6z1Hb+dC-=0g3rceGSyZ+dYHR=F8XNQvd4=0E=y9RaQ-pwA@mail.gmail.com>
Subject: Re: [oci-tob] image-spec maintainer gap
To: Vincent Batts <vbatts@hashbangbash.com>
Cc: Phil Estes <estesp@gmail.com>, Technical Oversight Board <tob@opencontainers.org>
I'm on PTO for a few days, so I'm not in a position to make the swap
myself. But I'm fine with this if someone else wants to do it.
```
**This PR must get at least 6 LGTMs before merging:**
Signed-off-by: Phil Estes <estesp@gmail.com>
> Replace Jason Bouzane with Jon Johnson in image-spec maintainers

- schema/error.go
The offset to line/col translation is easy to implement. Not worthy
to bring a third-party dependency.
PS. I think this code is never used, but removing it is too aggressive
since it exposes public api.
Signed-off-by: Shengjing Zhu <zhsj@debian.org>
> Remove go4.org dependency

- README.md
The OCI scope table no-longer exists.  Drop the
reference to it in the README.
Fixes #812
> Drop link to OCI scope table

- schema/descriptor_test.go
Just kidding, I can't sleep at night because of these things :P 
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
> Expected type/subtype test for descriptors should have comment that is failure

- spec.md
There doesn't seem to be an introduction in this file (and the link goes to itself?) so I think we probably want to remove it (or link to an introduction elsewhere?)
> Removing Link Introduction

- config.md
- conversion.md
- image-index.md
- schema/config-schema.json
- schema/config_test.go
- schema/fs.go
- schema/validator.go
- specs-go/v1/config.go
Carries #777 + adds other platform fields
Closes #777
> Embed platform fields in Image spec

- annotations.md
- specs-go/v1/annotations.go
Fixes #821 and #783 
As discussed in [yesterday's call](https://hackmd.io/El8Dd2xrTlCaCG59ns5cwg?view#February-17-2021), the next step was to open a PR to nail down specific wording.
> Add standard base image annotations

- config.md
- media-types.md
OCI media types are slightly different from Docker ones,
e.g., Docker manifests must have `.mediaType` field while OCI may not have.
Also, OCI descriptors may have `.annotations` while Docker may not.
> media-types.md: clarify differences from Docker media types

- .github/workflows/docs-and-linting.yml
- Makefile
the tool dep on `github.com/mjibson/esc` was failing on:
```
../../../golang.org/x/tools/internal/typeparams/normalize.go:138:17: u.EmbeddedType undefined (type *types.Interface has no field or method EmbeddedType)
```
> github: bring forward the versions of golang tested/built with

- descriptor.md
Fixed a minor typo / spelling mistake.
> Minor spelling correction

- README.md
The OCI scope table no-longer exists.
Fixes #812
Signed-off-by: sanshirookazaki <sanshirookazaki@gmail.com>
> README.md: Remove link to OCI scope table

- implementations.md
having seen #895, it's worth ensuring these other languages are listed
implementations
> implementations||adopters: point to C and Rust libraries

- descriptor.md
- specs-go/v1/descriptor.go
This should contain an embedded representation of the referenced
content, which is useful for avoiding extra hops to access small pieces
of content.
Fixes https://github.com/opencontainers/image-spec/issues/825
Closes #675
> Define the data field

- GOVERNANCE.md
- RELEASES.md
The current charter link is 404'ing: <https://www.opencontainers.org/about/governance>
This points to the git repo, which is the same location the website redirects to: <https://github.com/opencontainers/tob/blob/main/CHARTER.md>
> Fixing charter link

- image-index.md
- manifest.md
Updating example manifest JSON to include `mediaType` field to match the spec (which says `mediaType` SHOULD be included in the image manifest & image index).
> Add mediaType fields into example manifest & image index JSON references

- CODEOWNERS
- EMERITUS.md
- MAINTAINERS
As stated in [`EMRITUS.md`](https://github.com/opencontainers/image-spec/blob/main/EMERITUS.md):
> We would like to acknowledge previous OCI image spec maintainers and their huge contributions to our collective success ... We thank these members for their service to the OCI community.
The last activity from these maintainers appears to be Jun 30, 2017, which predates my involvement in this community. As we make progress in areas such as the [OCI Reference Types WG](https://github.com/opencontainers/wg-reference-types), it becomes critical to have active maintainers on this repository.
In my opinion, If you do not support this motion, it says a lot about your motivations and political agendas. Please consider this and do the right thing.
> Move inactive maintainers to emeritus

- HACKING.md
- README.md
- annotations.md
- considerations.md
- descriptor.md
- layer.md
- schema/config-schema.json
- schema/content-descriptor.json
- schema/image-index-schema.json
- schema/image-layout-schema.json
- schema/image-manifest-schema.json
- spec.md
Fixes #913 
I didn't touch the licensing links, and the broken link in the README.md (see #914).
> Update URLs to https

- Makefile
> Pinning version of golangci-lint to support 1.16

- .github/PULL_REQUEST_TEMPLATE/maintainer_nomination.md
This is a PR template to propose adding new maintainers
Fixes #912
Signed-off-by: nisha <nisha@ctlfsh.tech>
> Add maintainer nomination template

- CODEOWNERS
- EMERITUS.md
- MAINTAINERS
jdolitsky
sudo-bmitch
- Attendance in OCI weekly meetings
- Activity in image-spec/distribution-spec issues relating to extending specs
- Contributing to the OCI Reference Types working group
- Overall solid person
Need 3 approvals from the current 5 maintainers:
> Add Brandon as maintainer

- annotations.md
- artifact.md
- descriptor.md
- image-index.md
- manifest.md
- media-types.md
- specs-go/v1/annotations.go
- specs-go/v1/artifact.go
- specs-go/v1/descriptor.go
- specs-go/v1/manifest.go
- specs-go/v1/mediatype.go
This is a culmination of many people's work over the last few months to introduce reference types to OCI as part of the [OCI Reference Types WG](https://github.com/opencontainers/tob/blob/main/proposals/wg-reference-types.md).
This PR contains the changes from our chosen proposal, [Proposal E](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md), relevant to the image-spec. We're looking forward to hearing feedback from image-spec maintainers on these changes!
Associated distribution-spec PR - https://github.com/opencontainers/distribution-spec/pull/335
> Working Group Proposal for Reference Types

- image-layout.md
- schema/image-index-schema.json
- schema/image-manifest-schema.json
- schema/imageindex_test.go
- schema/manifest_test.go
Ideally it would be better to make the `mediaType` a required property. But given that we want to be backward compatible, the check is left to the client to ensure that layers/config doesn't appear with the manifests then mediaType is not present. 
This PR doesn't attempt to fix that requirement in the schema  and fixes only tests to have a valid mediaType. 
-- Signed-off-by: Sajay Antony <sajaya@microsoft.com>
> Update schema and tests for mediaType validation

- spec.md
This aligns the definitions in spec.md with the distribution-spec changes that were recently approved, and adds a link to the new artifact manifest.
> Add artifact to spec.md

- schema/loader.go
- schema/spec_test.go
- schema/validator.go
Resolves #943 
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> Remove io/ioutil references

- .github/workflows/docs-and-linting.yml
- Makefile
- go.mod
With Go releasing 1.19, the current supported versions are 1.18 and 1.19. I think we are staying 1 version behind supported, so this bumps to 1.17 with tests on 1.18 and 1.19. It also bumps up the GHA steps to the current versions.
> Bump from Go 1.16 to 1.17

- artifact.md
- manifest.md
- specs-go/v1/artifact.go
- specs-go/v1/manifest.go
Addresses the renaming of `refers` --> `subject`  for #940 
Signed-off-by: Sajay Antony <sajaya@microsoft.com>
> Rename refers field to subject

- config.md
*Some* of the sub-items of `config` were inconsistently indented (some using three spaces, some using two) -- adjusted to two to match the rest of the file.
> Fix whitespace consistency in config.md

- specs-go/version.go
Candidate commits for releasing `1.1.0-rc1` and switch back to dev and bump main branch version to `1.1.0-dev`
This follows precedence similar to - https://github.com/opencontainers/distribution-spec/pull/274/commits
Tied to https://github.com/opencontainers/distribution-spec/pull/348
> Release 1.1.0 rc1

- config.md
- media-types.md
- schema/config-schema.json
- specs-go/v1/config.go
This change officially adds ArgsEscaped to the image config. This field has already been used by Docker for several years, so adding it here allows images that depend on its behavior to work with other runtimes.
For certain Windows images created via Docker they may contain `ArgsEscaped==true` if the ENTRYPOINT or CMD is in the `shell` form and contains spaces, path characters, etc.
An example is the following:
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019
SHELL ["powershell", "-Command"]
ENTRYPOINT "C:\Path To\MyExe.exe" -arg1 "-arg2 value2"
```
Will be encoded by Docker as:
```
"Config": {
...
"ArgsEscaped": true,
...
"Entrypoint": [
"powershell.exe -Command \"C:\\My Data\\MyExe.exe\" -arg1 \"-arg2 value2\""
],
...
}
```
You can see that `Entrypoint` becomes a single element …
> Add ArgsEscaped field to image config

- specs-go/v1/config.go
- relates to the discussion on https://github.com/containerd/containerd/pull/7376#discussion_r966193773
This embeds the Platform struct in the image struct, so that these fields don't have to be defined multiple times, and to allow projects that have tooling for validating/normalizing/handling Platform data can apply these on an image-config, without first constructing a Platform from these fields.
> Embed Platform in Image

- image-index.md
As discussed in today's call.
Wasm (WebAssembly) is an exciting new space, and the Wasm community has smartly chosen to adopt OCI as a packaging and distribution format for Wasm applications.
Unfortunately, today, they mainly build applications using `docker build` and Dockerfiles where `.wasm` files are `COPY`ed onto `scratch` base images, resulting in images whose configs report them as `linux/amd64` images by default.
If Wasm applications want to be distributed alongside images for other platforms, especially alongside _actual_ `linux/amd64` images, this may be problematic.
Unfortunately, OCI's guidance around selecting a platform to report is lacking for this use case. Repurposing Go's set of supported `GOOS` and `GOARCH` values is insufficient here, since Go currently doesn't have …
> Note an exception to the platform.os recommendation for wasi

- layer.md
- media-types.md
Microsoft has announced their intention to change their image redistribution policy so that Windows images no longer make use of non-distributable layers: https://techcommunity.microsoft.com/t5/containers/announcing-windows-container-base-image-redistribution-rights/ba-p/3645201
@justincormack says:
> Foreign layers in OCI images can now be deprecated
- https://twitter.com/justincormack/status/1580536342114492417
This PR updates the spec to note that clients SHOULD NOT create new images with non-distributable layers. They may still need to handle them for old images created pre-this-deprecation however.
Please feel free to suggest better wording. 🚲🏠
> Deprecate non-distributable layers

- annotations.md
- specs-go/v1/annotations.go
See https://github.com/opencontainers/distribution-spec/pull/380 which proposes changing how the registry communicates that it applied filters to be "out-of-band" of the image manifest response, so this doesn't need to be documented in image-spec at all.
Signed-off-by: Jason Hall <jason@chainguard.dev>
> Remove filtersApplied from image-spec

- .github/workflows/docs-and-linting.yml
- Makefile
- go.mod
Added Go 1.20 to GitHub actions matrix and dropped Go 1.17
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> Add Go 1.20 support

- manifest.md
This guidance is carried over from the artifacts repo, and matches exactly the [guidance for artifact manifests](https://github.com/opencontainers/image-spec/blob/main/artifact.md#artifact-manifest-property-descriptions).
This is intended as progress toward https://github.com/opencontainers/artifacts/issues/63
Signed-off-by: Jason Hall <jason@chainguard.dev>
> Require IANA mediaType for image config.mediaType and layers.mediaType

- config.md
- conversion.md
This clarifies the behavior of supplemental groups when a primary group is specified.
The config part is implied by the text, and the conversion part seems to miss this corner case.
> Update image spec and conversion to clarify groups

- schema/validator.go
- specs-go/v1/config.go
- specs-go/v1/mediatype.go
Use the golang styling for deprecation notices. This way importing from this source as a library may give notice.
this is a continuation/cleanup of #892 and #965
> specs-go/v1/*.go: align the deprecation style

- go.mod
Fix go.mod - split direct/indirect dependencies
Clarify direct dependencies.
Signed-off-by: junya koyama <arukiidou@yahoo.co.jp>
> Chore: fix go.mod - split direct/indirect dependencies

- schema/image-manifest-schema.json
- schema/manifest_test.go
Fixes: #1018
This seems to have been missed through the WG PR.
> manifest schema: add the missing `subject` field

- descriptor.md
> descriptor: clarify `artifactType` field must have compliant values

- schema/config-schema.json
- schema/content-descriptor.json
- schema/image-index-schema.json
- schema/image-layout-schema.json
- schema/image-manifest-schema.json
From my previous change to switch to https, this field should not have been modified since it's an identifier in an upstream spec. For more details see the conversation over here: https://github.com/opencontainers/image-spec/pull/915#discussion_r869822840
> Reverting json schema to well known value

- schema/content-descriptor.json
- schema/defs.json
- schema/descriptor_test.go
> descriptor schema: add missing data and artifactType definitions

- manifest.md
- specs-go/v1/manifest.go
Through the conversations between artifact manifest and standardizing the misuse of the image-manifest one of the topics was around when there is _not_ a `config` needed for the `layers`/blobs, and if there was not a `layer` needed. How best to be portable.
Since the `config` is a REQUIRED field, it meant setting this to some valid value.
This guidance intends to set a norm for a blob that need only be pushed to a registry a single time, and then save on round trips for all future SCRATCH configs, while also being most widely portability.
> manifest: provide guidance on SCRATCH descriptor (config and layer)

- manifest.md
- specs-go/v1/manifest.go
This covers a few nits with the scratch variable and documentation on its usage. It also clarifies that various requirements on the layer blobs only apply when the config media type specifies the content is an OCI Image (vs using the image manifest to package an artifact).
> Rename the scratch variable and layer requirements

- media-types.md
The artifact manifest media type (and the `artifact.md`) was removed in https://github.com/opencontainers/image-spec/pull/999. This PR removes expired reference to them.
> Remove artifact media type reference

- specs-go/v1/descriptor.go
`ppc64` is not a valid architecture, but `ppc64le` is.
> Fix minor typo in doc comment of specs-go

- specs-go/version.go
this is would mean tagging 085b884 as v1.1.0-rc.3 (now with more SemVer)
fd45b6b Add scratch descriptor and scope layer limits
63b8bd0 Remove artifact manifest
23c4647 Define image manifest artifactType and guidance
5751791 Add Tianon as maintainer
f4fc83a Fix unused variable linting error
d09d13d Update Jon Johnson's email
4136bec descriptor schema: add missing data and artifactType definitions
729a03e manifest, specs-go/: provide guidance on SCRATCH config descriptor
31de013 manifest schema: add tests for the subject field
7a9efbd manifest schema: add the missing `subject` field
f2f1956 descriptor: clarify artifactType field must have compliant values
98f35df Update image spec and conversion to clarify groups
336b02c Require IANA mediaType for image config.mediaType and layers.mediaType …
> tag v1.1.0-rc.3

- image-index.md
Go is going to support a platform like `wasip1/wasm`, `wasip2/wasm`, and eventually `wasi/wasm`. We should remove the guidance that Wasm is a special case, and fallback to following Go's guidance when describing a platform.
Fixes https://github.com/opencontainers/image-spec/issues/1053
This exception was added in https://github.com/opencontainers/image-spec/pull/964 -- see there for original (outdated!) discussion.
> Remove special guidance around wasm

- manifest.md
It looks like we documented the content of the scratch blob when talking about the config descriptor, but not in the scratch descriptor section.
> Specify the content of the scratch blob

- RELEASES.md
Under SemVer, the suffix "-dev" actually indicates a pre-release, meaning the way we've been using the suffix indicates that "1.0.0-dev" is *older* than "1.0.0" when we've used the suffix to indicate the opposite.
With most package managers, the "+dev" suffix correctly indicates that the version is newer (i.e. 1.0.1 > 1.0.0+dev > 1.0.0), though under SemVer "+dev" build tags must be ignored when doing version comparisons (meaning 1.0.0+dev == 1.0.0 under SemVer). However,  from a SemVer perspective the unreleased version is inarguably closer to being equal to the last release than being older than it. As a specification we also allow extensibility of various parts, meaning that if someone uses an as-yet-unreleased version it seems reasonable to me for it to be treated as the same (from a …
> releases: use +dev as in-development suffix

- specs-go/version.go
#1050 updates the release instructions. This applies the change to the version.go.
> Apply version change from #1050

- manifest.md
- media-types.md
- schema/manifest_test.go
- specs-go/v1/descriptor.go
- specs-go/v1/manifest.go
- specs-go/v1/mediatype.go
Here's an attempt to resolve #1067. I originally picked "filler" for the new name, but the community prefers "empty".
> Switch from scratch to empty

- image-index.md
It would be useful for implementations which generate multiple artifacts, each with their own platform or other metadata and perhaps, associated signatures, attestations, to be able to index them all in a single image index.
As an implementer, I'm considering having a top level "package" stored as an image index, which then references all the artifacts in the package as artifacts (image manifests). The artifactType of the image index would be "application/...package", and the artifactType of the image manifests could be:
* "application/...plugin" with annotations and/or platform fields set to indicate that it is the plugin for, e.g., macOS with Apple Silicon (darwin-arm64)
* "application/...schema" with annotations indicating this is a separate artifact
* ... other artifact types as …
> Add artifactType to image index

- image-index.md
- schema/image-index-schema.json
- specs-go/v1/index.go
Fixes: #1002
This allows for an image-index / manifest-list (_still_ the better name than "image-index" ...) to point to the blob of another manifest. This is a part of the referrer API in the distribution-spec.
> image-index: add the `subject` field

- config.md
- considerations.md
- image-index.md
- image-layout.md
- manifest.md
Implementations lack any information to determine whether the `config` property of an Image Manifest describes the `artifactType` of the manifest, or the media type of the referenced content. This is necessitated by the removal of artifact manifest (#999) and addition of scratch descriptors (#1023) to support artifacts.
If #999 is withdrawn, this pull request should be withdrawn as well and #1028 considered instead.
> image manifest: support use as artifact

- schema/image-index-schema.json
- schema/imageindex_test.go
- specs-go/v1/index.go
> image-index: add artifactType to specs and schema

- specs-go/v1/annotations.go
Duplicated annotations that needed to be removed since Manifest/image is now accepted as a generic manifest as a part of #999 and related to #980
> specs-go: remove artifact prefixed annotations

- specs-go/v1/layout.go
The [layout spec](https://github.com/opencontainers/image-spec/blob/v1.0/image-layout.md#content) requires three named files/directories. The `oci-layout` file name is already exposed as a constant from this package. This PR adds exported constants for `index.json` and `blobs`.
Closes #1069
> Add constants for "index.json" and "blobs" alongside "oci-layout" as parts of the layout specification

- schema/imageindex_test.go
- schema/manifest_test.go
This adds missing tests for the subject field on the image index. It also moved the field before annotations for consistency in the image manifest tests.
> Test subject field in index

- specs-go/version.go
This would mean tagging 82e8329 as v1.1.0-rc4
988df0a  specs-go: remove artifact prefixed annotations
25fc553 Switch from scratch to empty
a68ca3e Remove artifact media type reference
a845c7a  image-index: add artifactType to specs and schema
749ea9a Add artifactType to image index
32036d8 Apply version change from #1050
f3f0906 Specify the content of the scratch blob
e13840d Add language from artifacttype field to forbid allowlists of media types
77efc6e spec: clarify descriptor, align with de facto artifact usage
29a1380 Remove special guidance around wasm
2720969 Update descriptor.go
428b1e5 releases: use +dev as in-development suffix
2f691e8 version: bump HEAD back to -dev
c6854a6 image-index: add the `subject` field
[v1.1.0-rc3..82e8329](https://github.com/opencontainers/image-spec/co …
> tag 1.1.0-rc4

- image-index.md
Several of the link references were copied from other docs without copying the link itself. I also cleaned up a markdown lint requesting white space around code blocks.
> Cleanup broken links and markdown spacing in image-index

- .golangci.yml
Running the lint check was generating the following errors:
```
checking lint
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
```
Fixes #1086
> Remove deprecated golangci lint checks

- specs-go/v1/descriptor.go
In the descriptor, mediaType is required according to the spec. This aligns the Go implementation to the JSON schema and markdown spec.
> MediaType is required in the descriptor

- considerations.md
Fix spelling, markdown spacing, consistent bullets, code block language hints, and move links to the end.
> Clean up the markdown in considerations

- annotations.md
This fixes the label schema link since the project is now archived and certificates are unlikely to be fixed. It also adjusts some markdown syntax with links at the end and whitespace after headers.
Fixes #978.
> Fix label schema link

- GOVERNANCE.md
This is changes to the governance doc, but they are all superficial, so I'm not sure of the voting requirements for that. The changes are:
- Email addresses should be enclosed in brackets, same as links.
- Release approval header missing, replaced with proposing a motion.
- Replaced runtime-spec with image-spec in examples.
- Proposing a motion header was in the document twice, renamed.
> Cleanup markdown in governance

- HACKING.md
- Makefile
The hacking.md doc had some stale references that needed to the cleaned. That resulted in the following changes:
- Remove/replace stale references from hacking doc.
- Add spacing for markdown.
- Add code block language for syntax highlighting.
- Remove leading "$ " from commands without output.
- Move links to end.
- Switch to automatically generated help in Makefile.
> Hacking markdown and Makefile cleanup

- descriptor.md
On descriptor.md, the link for `canonicalization` was pointing a non-existing file.
Found where the content was moved to and update the link.
> chore(descriptor.md): correct canonicalization reference

- README.md
Good news! OCI has a distribution-spec.
> OCI has a distribution-spec

- artifacts-guidance.md
- spec.md
This adds a destination for the link in https://github.com/opencontainers/artifacts/pull/68. This will be easier to update later, e.g. moving the guidance out of manifest.md, or adding guidance for using an index when we have examples of that, without needing to modify a link in an archived project.
> Create artifacts guidance

- Makefile
This avoids a potential foot gun, where a future md file in a sub directory would match the wildcard in the shell, and not pass the expression to the linter. I ran into this when setting up the linter on the wg-auth repo.
> Quote lint-md wildcard expression

- artifacts-guidance.md
- manifest.md
This adds a decision tree to the artifact guidance to indicate when the artifactType field should and should not be used. I believe this closes #1100.
> Provide a decision tree for artifacts

- Makefile
This fixes a CI failure that started with the latest golangci-lint release.
> Fix golangci-lint install on older versions of Go

- conversion.md
- descriptor.md
- add missing left-border
- align columns
looks like the linter added in a6af2b480dcfc001ba975f44de53001c873cb0ef may not handle tables; rendering still looked good, so Markdown is probably flexible enough to allow omitting the border on one side.
> fix markdown table formatting

- specs-go/v1/mediatype.go
Reorganise order of MediaTypes:
Move the deprecated types in a single group, and move the non-deprecated types to the section with non-deprecated manifests / desrciptors.
> specs-go: group MediaTypes

- implementations.md
[ORAS](https://oras.land/) is an OCI registry client and a set of libraries that provide a way to distribute OCI Artifacts to and from OCI Registries. It is a CNCF Sandbox project. ORAS is compliant with OCI [image-spec v1.1.0-rc4](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/manifest.md#oci-image-manifest-specification) and [distribution-spec v1.1.0-rc3](https://github.com/opencontainers/distribution-spec/tree/v1.1.0-rc3).
> add ORAS to implementations.md

- Makefile
"call me Mr. Nit-Pick"
Sorry for the very minor PR, but this one was driving me nuts as my IDE kept stripping it when working on the Makefile, so let's stop this fight between my IDE and the repository, and settle this once and for all 😂 
Thank you `git`, you were a worthy contender.
> Makefile: remove stray trailing space

- .github/workflows/docs-and-linting.yml
This prevents Go from doing an automatic upgrade, giving a better test of backwards compatibility. Related to https://github.com/opencontainers/image-spec/pull/1114#pullrequestreview-1639441396
> Test older versions of Go with toolchain=local

- .github/workflows/docs-and-linting.yml
This updates the supported Go range to 1.19 - 1.21. The previous supported range was 1.18 - 1.20.
> Update supported Go range to 1.19 - 1.21

- implementations.md
Update md since CoreOS rkt got dismantled, and there are no plans to push the development forward.
Also in the CNCF landscape, the project is marked as [Project ended]
Fixes #1096
> update implementations rkt project has ended

- RELEASES.md
We need to be sure to update the website after we push releases. This adds the step to our release process.
> Add step to update website after a release

- specs-go/version.go
6c2b5fa as v1.1.0-rc6
53d9855 new section for projects no longer maintained (#1148)
b391bc0 fix: SPDX licenses URL (#1146)
dd66b54 Test older versions of Go with toolchain=local (#1133)
93f6e65 Makefile: remove stray trailing space (#1126)
d881fa8 deps: remove deprecated github.com/pkg/errors (#1125)
072574d add ORAS to implementations.md (#1122)
9954739 specs-go: group MediaTypes (#1118)
344b098 fix markdown table formatting (#1117)
c7a064f Update supported Go range to 1.19 - 1.21 (#1114)
f0ef80e version: bump back to +dev (#1109)
a2a5750 Add step to update website after a release (#1107)
Diff: https://github.com/opencontainers/image-spec/compare/v1.1.0-rc5...6c2b5fa
Mailing list: https://groups.google.com/a/opencontainers.org/g/dev/c/HOxZlfhr9-o
Votes:
> Release v1.1.0-rc6

- image-index.md
- manifest.md
This is resolving concerns raised in https://github.com/opencontainers/distribution-spec/pull/502 and discussed on today's meeting.
> Clarify that subject references a separate DAG

- specs-go/version.go
This thread tracks the release votes: https://groups.google.com/a/opencontainers.org/g/dev/c/Cnk6H9C4aag
e7f7c0c  as v1.1.0
Last release for Image-spec was v1.02 -  https://github.com/opencontainers/image-spec/pull/878. 
- For full diff from v1.0.2 - https://github.com/opencontainers/image-spec/compare/opencontainers:image-spec:v1.0.2...sajayantony:image-spec:release-v1.1.0
- Commits after the last v1.1.0-rc.6 - https://github.com/opencontainers/image-spec/compare/opencontainers:image-spec:v1.1.0-rc6...sajayantony:image-spec:release-v1.1.0
0a41c19  version: bump back to +dev - Sajay Antony
e7f7c0c  version: release v1.1.0 - Sajay Antony
d0f90e6  Clarify that subject references a separate DAG - Brandon Mitchell
8b1e951  version: bump back to +dev - Brandon Mitchell
Votes:
Associated …
> Release v1.1.0

- Makefile
Fixes CI issue blocking #1165
This changes pins golangci-lint to v1.55.2 for Go v1.20 to resolve CI issues where golangci-lint v1.56.1 requires Go v1.21 or higher.
> Pin golangci-lint for Go v1.20

- media-types.md
Related to https://github.com/distribution/distribution/pull/4101, This PR move `spec/manifest-v2-2.md` to `content/spec/manifest-v2-2.md`
> media-types: Fix broken links

- .github/workflows/docs-and-linting.yml
N/A
This change updates actions/checkout to v4, actions/setup-go to v5, and actions/upload-artifacts to v4 to resolve NodeJS 16 deprecation warnings in CI.
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update GitHub Actions packages to resolve warnings in CI

- manifest.md
The `config` digest is used by a number of popular runtimes/orchestrators as an identifier for an image with an amount of assumed uniqueness.
> Add note about `ImageID` to the `config` section of `manifest.md`

- .github/workflows/docs-and-linting.yml
This is a follow up to #1166 and fixes a remaining item from #1165. It supports current Go releases and 1.18, upgrades the upload-artifact workflow, but only runs that workflow for the latest Go version.
> Update Go versions in release scripts

- CODEOWNERS
- EMERITUS.md
- MAINTAINERS
Glad to have been part of this project, but it's time to recuse myself
from maintainership and make way for folks more active and engaged in
this space. Follows #1177.
>     MAINTAINERS: move jonboulle to EMERITUS

- schema/validator.go
Based on our discussion on the June 6th call, we decided to remove the warnings from the code and focus on only things that trigger an error. We had not been maintaining the existing warnings. Anything that only prints to stdout/stderr was deleted since it's unlikely anyone is using that. Private functions that only triggered a print to stdout were deleted.
If others want a stricter validation, those on the call felt it would be better for them to perform that themselves rather than adding new code for OCI to maintain.
Fixes #686.
> Remove validation warnings to stdout

- annotations.md
~~See b692deece6f3e93d43de1615fa592b86f0f27c34 (https://github.com/opencontainers/image-spec/pull/695) for where this was originally added (making clear this was the original intent).~~
~~IMO it _slightly_ conflicts with the bullet point above it being simply SHOULD, but it has been part of the spec since v1.0 (and in a disagreement between MUST and SHOULD, the stronger constraint wins and that's MUST).~~
Updated: https://github.com/opencontainers/image-spec/pull/1196#pullrequestreview-2243187911
> Remove misleading "must" in `ref.name` requirements

- .github/workflows/docs-and-linting.yml
- Makefile
This fixes the broken linter. As the comment says on the matrix, I'm testing the currently supported Go releases plus the one in our go.mod: https://github.com/opencontainers/image-spec/blob/main/go.mod#L3
> Update linter and Go releases

- layer.md
- manifest.md
This highlights that nondistributable layers have been deprecated in other parts in the spec.
> Add deprecation notices to nondistributable layers

- manifest.md
> Implementations should support zstd

- .tool/pin-release.sh
- RELEASES.md
This pins references to external specs (distribution and runtime) to their latest release on a release of this project.
See the discussion on #1207 for more context.
> Feat: Pin external references on a release

- README.md
- conversion.md
- image-layout.md
- spec.md
- Updated several links in README.md, conversion.md, image-layout.md, and spec.md to point to the 'main' branch of the runtime-spec repository.
- Replaced outdated 'master' and 'v1.0.0' references with 'main' for consistency with the latest branch structure.
> README: update runtime-spec links to use main branch

- layer.md
I found it confusing that the first example given for the whiteouts section was only about opaque whiteouts even though that gets its own section. So I added a simple example with just a file and directory being deleted.
The second commit fixes what I believe is a typo in the opaque whiteout example, where it says that `a/b` is deleted, but I think it is `a/` that is deleted.
> Suggested clarification to whiteouts

- layer.md
Fixes #1204.
This calls out the limitations of hard links in a union filesystem. E.g. in some configurations a hard link may be broken when multiple files are hard linked and a change is made to one file or a hard link is created to a lower filesystem file. See https://docs.kernel.org/filesystems/overlayfs.html#index
> Hard link limitations in union filesystems

- .github/workflows/docs-and-linting.yml
`actions/setup-go` supports "stable" and "oldstable" as automatic aliases for the latest release and the previous to latest release, which was our intent with two of these three hard-coded versions.  The third is hard-coded to match our `go.mod`, which `actions/setup-go` *also* supports reading from, so we can be completely DRY here.
See https://github.com/opencontainers/image-spec/pull/1225#discussion_r1882995860
> Reduce maintenance burden by letting setup-go track our Go versions

- descriptor.md
> Manifests may contain multiple digest algorithms

- image-layout.md
Implementations have been seen that error if a `manifest.json` is included inside the OCI Layout. This documents the extensibility of the directory structure.
See https://github.com/moby/moby/issues/49141
> Document extensibility of the image layout

- HACKING.md
- go.mod
> Document Go version policy

- config.md
Total nit but thought I'd tweak cause I noticed it
`This field` reads more naturally than `The field`, and it's consistent with the use of `This field` and `This property` throughout the rest of the document
> Fix grammar nit

- descriptor.md
Motivations for this PR:
1. Blake3 is a high performance hash and there is growing community interest
2. Blake3 is variable output, but mandate 256-bit output
> Add blake3 as a registered/supported hash algorithm.

- .github/workflows/docs-and-linting.yml
- README.md
- remove meaningless badge
- also lint/test pushes (not just PRs)
- allow running the job explicitly on-demand ("workflow dispatch")
- cancel in-progress runs on PR update / push to the same branch
- explicitly limit GitHub token permissions
See also https://github.com/opencontainers/image-spec/pull/1251
> Update GitHub Actions configuration

- image-layout.md
Quick fix for a broken relative link.
> Fix: correct a broken link to "applying changesets"

- .github/workflows/docs-and-linting.yml
- HACKING.md
- Makefile
- go.mod
- go.sum
- schema/defs-descriptor.json
- schema/go.mod
- schema/go.sum
- schema/spec_test.go
- schema/validator.go
`github.com/santhosh-tekuri/jsonschema/v5` is about 2 years old, `github.com/russross/blackfriday` more than 4 years old. Keeping up will only get harder as the users stay behind.
Note a possible downside: The `v6` of the JSON schema parser imports `golang.org/x/text` to support localized error messages, and that is +17570 of a dependency.
Warning: I am not an expert in either of the packages, I was looking for the most similar new APIs. (I did manually verify that the markdown parsing produces the same code examples.)
> Update 2 dependencies
